/**
 * BOQ Excel Generator
 * Produces a properly formatted, editable .xlsx BOQ from structured JSON data.
 * Uses ExcelJS. Install: npm install exceljs
 */
const ExcelJS = require('exceljs');

const NAVY = 'FF1B2A4A';
const LIGHT_BLUE = 'FFD6E4F0';
const YELLOW = 'FFFFF2CC';
const WHITE = 'FFFFFFFF';
const BORDER_COL = 'FFCBD5E1';

const thin = { style: 'thin', color: { argb: BORDER_COL } };
const borders = { top: thin, bottom: thin, left: thin, right: thin };

const COLS = [
  { key: 'item', width: 8 },
  { key: 'description', width: 48 },
  { key: 'unit', width: 8 },
  { key: 'qty', width: 10 },
  { key: 'rate', width: 12 },
  { key: 'labour', width: 14 },
  { key: 'materials', width: 14 },
  { key: 'total', width: 14 },
  { key: 'source', width: 14 },
];

function hdrFont() { return { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } }; }
function stdFont(b) { return { name: 'Arial', size: 10, bold: !!b, color: { argb: 'FF1E293B' } }; }
function currFmt() { return '#,##0.00'; }

function styleRow(row, fill, bold) {
  row.eachCell((c, col) => {
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: fill } };
    c.font = fill === NAVY ? hdrFont() : stdFont(bold);
    c.border = borders;
    c.alignment = { vertical: 'middle', wrapText: col === 2 };
    if ([5, 6, 7, 8].includes(col)) { c.numFmt = currFmt(); c.alignment = { horizontal: 'right', vertical: 'middle' }; }
    if (col === 4) { c.numFmt = '#,##0.00'; c.alignment = { horizontal: 'center', vertical: 'middle' }; }
    if ([1, 3, 9].includes(col)) c.alignment = { horizontal: 'center', vertical: 'middle' };
  });
}

async function generateBOQExcel(sections, projectName, clientName, opts = {}) {
  const currency = opts.currency || '£';
  const contingencyPct = opts.contingency_pct || 7.5;
  const ohpPct = opts.ohp_pct || 12;
  const vatRate = opts.vat_rate || 20;

  const wb = new ExcelJS.Workbook();
  wb.creator = 'The AI QS';
  wb.calcProperties = { fullCalcOnLoad: true };
  const ws = wb.addWorksheet('BOQ', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  });
  ws.columns = COLS.map(c => ({ width: c.width }));

  // Title block
  const t1 = ws.addRow([`Bill of Quantities — ${projectName}`]);
  ws.mergeCells(t1.number, 1, t1.number, 9);
  t1.getCell(1).font = { name: 'Arial', size: 14, bold: true, color: { argb: NAVY.slice(2) } };
  t1.height = 30;

  const t2 = ws.addRow([`Client: ${clientName}    |    Date: ${new Date().toLocaleDateString('en-GB')}    |    Generated by The AI QS`]);
  ws.mergeCells(t2.number, 1, t2.number, 9);
  t2.getCell(1).font = { name: 'Arial', size: 10, color: { argb: 'FF64748B' } };
  ws.addRow([]);

  // Column headers
  const headers = ['Item', 'Description', 'Unit', 'Qty', `Rate (${currency})`, `Labour (${currency})`, `Materials (${currency})`, `Total (${currency})`, 'Rate Source'];
  const hr = ws.addRow(headers);
  styleRow(hr, NAVY, true);
  hr.height = 28;
  const headerRowNum = hr.number;

  // Data rows
  const subtotalRows = [];

  for (const section of sections) {
    // Section header
    const sr = ws.addRow([section.number || '', section.title || 'Untitled Section', '', '', '', '', '', '', '']);
    ws.mergeCells(sr.number, 2, sr.number, 9);
    styleRow(sr, LIGHT_BLUE, true);
    sr.height = 22;

    const firstData = ws.lastRow.number + 1;
    const items = section.items || [];

    for (const item of items) {
      const labour = parseFloat(item.labour) || 0;
      const materials = parseFloat(item.materials) || 0;
      const total = parseFloat(item.total) || (labour + materials) || ((parseFloat(item.qty) || 0) * (parseFloat(item.rate) || 0));

      let srcLabel = '◇ Generic';
      if (item.rate_source === 'verified' || (item.rate_source && item.rate_source.includes('verified'))) srcLabel = '✓ Verified';
      else if (item.rate_source === 'emerging' || (item.rate_source && item.rate_source.includes('emerging'))) srcLabel = '⚠ Emerging';
      else if (item.rate_source === 'client' || (item.rate_source && item.rate_source.includes('your'))) srcLabel = '✓ Client';

      const dr = ws.addRow([
        item.item || '', item.description || '', item.unit || '',
        parseFloat(item.qty) || '', parseFloat(item.rate) || '',
        labour || '', materials || '', total || '', srcLabel
      ]);
      dr.eachCell((c, col) => {
        c.font = stdFont(false);
        c.border = borders;
        c.alignment = { vertical: 'middle', wrapText: col === 2 };
        if ([5, 6, 7, 8].includes(col)) { c.numFmt = currFmt(); c.alignment = { horizontal: 'right', vertical: 'middle' }; }
        if (col === 4) { c.numFmt = '#,##0.00'; c.alignment = { horizontal: 'center', vertical: 'middle' }; }
        if ([1, 3].includes(col)) c.alignment = { horizontal: 'center', vertical: 'middle' };
        if (col === 9) {
          const bg = srcLabel.includes('Verified') || srcLabel.includes('Client') ? 'FFD1FAE5' : srcLabel.includes('Emerging') ? 'FFFEF3C7' : 'FFF1F5F9';
          c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } };
          c.alignment = { horizontal: 'center', vertical: 'middle' };
        }
      });
    }

    const lastData = ws.lastRow.number;
    if (items.length > 0) {
      // Calculate actual totals for cached values
      let labourSum = 0, matSum = 0, totalSum = 0;
      for (const item of items) {
        labourSum += parseFloat(item.labour) || 0;
        matSum += parseFloat(item.materials) || 0;
        totalSum += parseFloat(item.total) || (parseFloat(item.labour) || 0) + (parseFloat(item.materials) || 0) || ((parseFloat(item.qty) || 0) * (parseFloat(item.rate) || 0));
      }

      const sub = ws.addRow([
        '', `${section.title} — Subtotal`, '', '', '',
        { formula: `SUM(F${firstData}:F${lastData})`, result: labourSum },
        { formula: `SUM(G${firstData}:G${lastData})`, result: matSum },
        { formula: `SUM(H${firstData}:H${lastData})`, result: totalSum },
        ''
      ]);
      styleRow(sub, YELLOW, true);
      sub.height = 22;
      subtotalRows.push(sub.number);
    }
    ws.addRow([]);
  }

  // Summary — calculate cached values so they display without recalc
  ws.addRow([]);
  const sumHdr = ws.addRow(['', 'PROJECT SUMMARY', '', '', '', '', '', '', '']);
  ws.mergeCells(sumHdr.number, 2, sumHdr.number, 9);
  styleRow(sumHdr, LIGHT_BLUE, true);

  // Calculate net total from all section items
  let netTotal = 0;
  for (const section of sections) {
    for (const item of (section.items || [])) {
      netTotal += parseFloat(item.total) || ((parseFloat(item.labour) || 0) + (parseFloat(item.materials) || 0)) || ((parseFloat(item.qty) || 0) * (parseFloat(item.rate) || 0));
    }
  }

  const contAmt = netTotal * (contingencyPct / 100);
  const ohpAmt = netTotal * (ohpPct / 100);
  const grandTotal = netTotal + contAmt + ohpAmt;
  const vatAmt = grandTotal * (vatRate / 100);
  const inclVat = grandTotal + vatAmt;

  const netFormula = subtotalRows.map(r => `H${r}`).join('+');
  const netRow = ws.addRow(['', 'Net Construction Cost', '', '', '', '', '', { formula: netFormula, result: netTotal }, '']);
  netRow.eachCell(c => { c.font = stdFont(true); c.border = borders; });
  netRow.getCell(8).numFmt = currFmt();
  const nrn = netRow.number;

  const contRow = ws.addRow(['', `Contingency (${contingencyPct}%)`, '', '', '', '', '', { formula: `H${nrn}*${contingencyPct/100}`, result: contAmt }, '']);
  contRow.eachCell(c => { c.font = stdFont(false); c.border = borders; });
  contRow.getCell(8).numFmt = currFmt();

  const ohpRow = ws.addRow(['', `Overheads & Profit (${ohpPct}%)`, '', '', '', '', '', { formula: `H${nrn}*${ohpPct/100}`, result: ohpAmt }, '']);
  ohpRow.eachCell(c => { c.font = stdFont(false); c.border = borders; });
  ohpRow.getCell(8).numFmt = currFmt();

  const gtRow = ws.addRow(['', 'GRAND TOTAL (Excl. VAT)', '', '', '', '', '', { formula: `H${nrn}+H${contRow.number}+H${ohpRow.number}`, result: grandTotal }, '']);
  styleRow(gtRow, YELLOW, true);
  gtRow.getCell(8).numFmt = currFmt();
  gtRow.getCell(2).font = { name: 'Arial', size: 11, bold: true, color: { argb: NAVY.slice(2) } };

  const vatRow = ws.addRow(['', `VAT (${vatRate}%)`, '', '', '', '', '', { formula: `H${gtRow.number}*${vatRate/100}`, result: vatAmt }, '']);
  vatRow.eachCell(c => { c.font = stdFont(false); c.border = borders; });
  vatRow.getCell(8).numFmt = currFmt();

  const inclRow = ws.addRow(['', 'TOTAL (Incl. VAT)', '', '', '', '', '', { formula: `H${gtRow.number}+H${vatRow.number}`, result: inclVat }, '']);
  styleRow(inclRow, YELLOW, true);
  inclRow.getCell(8).numFmt = currFmt();
  inclRow.getCell(2).font = { name: 'Arial', size: 11, bold: true, color: { argb: NAVY.slice(2) } };

  // Legend
  ws.addRow([]); ws.addRow([]);
  const lg = ws.addRow(['', 'Rate Source Legend:']);
  lg.getCell(2).font = { name: 'Arial', size: 9, bold: true };
  for (const [label, colour] of [['✓ Verified = Client-confirmed rate', '059669'], ['⚠ Emerging = Client rate, calibrating', 'D97706'], ['◇ Generic = UK database rate', '64748B']]) {
    const r = ws.addRow(['', label]);
    r.getCell(2).font = { name: 'Arial', size: 9, color: { argb: 'FF' + colour } };
  }

  // Print setup
  ws.headerFooter.oddFooter = '&LThe AI QS — theaiqs.co.uk&RPage &P of &N';
  ws.views = [{ state: 'frozen', ySplit: headerRowNum, activeCell: 'A' + (headerRowNum + 1) }];

  return await wb.xlsx.writeBuffer();
}

module.exports = { generateBOQExcel };
