/**
 * BOQ Excel Generator - Simple reliable approach
 * Uses ExcelJS with minimal formatting to ensure file validity
 */
const ExcelJS = require('exceljs');

async function generateBOQExcel(sections, projectName, clientName, opts = {}) {
  const currency = opts.currency || '\u00a3';
  const contingencyPct = opts.contingency_pct || 7.5;
  const ohpPct = opts.ohp_pct || 12;
  const vatRate = opts.vat_rate || 20;

  const wb = new ExcelJS.Workbook();
  wb.creator = 'The AI QS';
  wb.created = new Date();
  
  const ws = wb.addWorksheet('BOQ', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 }
  });

  // Column definitions — tightened so Total (col H) is visible on mobile screens
  // Description reduced from 62→48, Labour/Materials reduced from 14→12
  ws.columns = [
    { header: 'Item', key: 'item', width: 7 },
    { header: 'Description', key: 'desc', width: 48 },
    { header: 'Unit', key: 'unit', width: 6 },
    { header: 'Qty', key: 'qty', width: 8 },
    { header: 'Rate (' + currency + ')', key: 'rate', width: 10 },
    { header: 'Labour (' + currency + ')', key: 'labour', width: 12 },
    { header: 'Materials (' + currency + ')', key: 'materials', width: 12 },
    { header: 'Total (' + currency + ')', key: 'total', width: 13 },
    { header: 'Rate Source', key: 'source', width: 12 }
  ];

  // Colours
  var NAVY = 'FF1B2A4A';
  var SECTION_BG = 'FFD6E4F0';
  var SUBTOTAL_BG = 'FFFFF2CC';
  var VERIFIED_BG = 'FFD1FAE5';
  var EMERGING_BG = 'FFFEF3C7';
  var GENERIC_BG = 'FFF1F5F9';
  var BORDER_COL = 'FFCBD5E1';
  
  var thinBorder = { style: 'thin', color: { argb: BORDER_COL } };
  var allBorders = { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder };
  var currFmt = '#,##0.00';
  var qtyFmt = '#,##0.00';

  // Helper: apply borders and number format to a row
  function formatDataRow(row) {
    for (var c = 1; c <= 9; c++) {
      var cell = row.getCell(c);
      cell.border = allBorders;
      cell.font = { name: 'Arial', size: 10 };
      cell.alignment = { vertical: 'middle', wrapText: c === 2 };
      if (c >= 5 && c <= 8) {
        cell.numFmt = currFmt;
        cell.alignment = { horizontal: 'right', vertical: 'middle' };
      }
      if (c === 4) {
        cell.numFmt = qtyFmt;
        cell.alignment = { horizontal: 'center', vertical: 'middle' };
      }
      if (c === 1 || c === 3 || c === 9) {
        cell.alignment = { horizontal: 'center', vertical: 'middle' };
      }
    }
  }

  // === ROW 1: Title ===
  var row = 1;
  ws.mergeCells('A1:I1');
  var titleCell = ws.getCell('A1');
  titleCell.value = 'Bill of Quantities - ' + projectName;
  titleCell.font = { name: 'Arial', size: 14, bold: true, color: { argb: '1B2A4A' } };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  ws.getRow(1).height = 30;

  // === ROW 2: Client/Date ===
  ws.mergeCells('A2:I2');
  var infoCell = ws.getCell('A2');
  infoCell.value = 'Client: ' + clientName + '  |  Date: ' + new Date().toLocaleDateString('en-GB') + '  |  Generated by The AI QS';
  infoCell.font = { name: 'Arial', size: 10, color: { argb: '64748B' } };
  ws.getRow(2).height = 20;

  // === ROW 3: Blank ===
  row = 4;

  // === ROW 4: Column Headers ===
  var hdrRow = ws.getRow(row);
  hdrRow.values = ['Item', 'Description', 'Unit', 'Qty', 'Rate (' + currency + ')', 'Labour (' + currency + ')', 'Materials (' + currency + ')', 'Total (' + currency + ')', 'Rate Source'];
  hdrRow.height = 26;
  for (var h = 1; h <= 9; h++) {
    var hCell = hdrRow.getCell(h);
    hCell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    hCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    hCell.border = allBorders;
    hCell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  var headerRowNum = row;
  row++;

  // === DATA ROWS ===
  var subtotalRows = [];

  for (var si = 0; si < sections.length; si++) {
    var section = sections[si];
    
    // Section header
    var secRow = ws.getRow(row);
    ws.mergeCells('A' + row + ':I' + row);
    // Format section title: "1. PRELIMINARY WORKS & TRAFFIC MANAGEMENT" style (number + uppercase descriptive title)
    // Format section title: "1. 1. PRELIMINARY WORKS & TRAFFIC MANAGEMENT" style
    var secNum = section.number || String(si + 1);
    var secTitle = (section.title || 'Section').toUpperCase();
    secRow.getCell(1).value = secNum + '. ' + secTitle;
    secRow.getCell(1).font = { name: 'Arial', size: 10, bold: true, color: { argb: '1B2A4A' } };
    secRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
    secRow.getCell(1).border = allBorders;
    secRow.height = 22;
    row++;

    var firstItemRow = row;
    var items = section.items || [];

    for (var ii = 0; ii < items.length; ii++) {
      var item = items[ii];
      var labour = parseFloat(item.labour) || 0;
      var materials = parseFloat(item.materials) || 0;
      var total = parseFloat(item.total) || (labour + materials) || ((parseFloat(item.qty) || 0) * (parseFloat(item.rate) || 0));

      var srcLabel = 'Generic';
      if (item.rate_source === 'verified') srcLabel = 'Verified';
      else if (item.rate_source === 'emerging') srcLabel = 'Emerging';
      else if (item.rate_source === 'client') srcLabel = 'Client';

      var dataRow = ws.getRow(row);
      dataRow.getCell(1).value = item.item || '';
      dataRow.getCell(2).value = item.description || '';
      dataRow.getCell(3).value = item.unit || '';
      dataRow.getCell(4).value = parseFloat(item.qty) || 0;
      dataRow.getCell(5).value = parseFloat(item.rate) || 0;
      dataRow.getCell(6).value = labour;
      dataRow.getCell(7).value = materials;
      dataRow.getCell(8).value = total;
      dataRow.getCell(9).value = srcLabel;
      
      formatDataRow(dataRow);
      
      // Colour the source cell
      var srcBg = srcLabel === 'Verified' || srcLabel === 'Client' ? VERIFIED_BG : srcLabel === 'Emerging' ? EMERGING_BG : GENERIC_BG;
      dataRow.getCell(9).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: srcBg } };
      
      row++;
    }

    var lastItemRow = row - 1;

    // Section subtotal
    if (items.length > 0) {
      var subRow = ws.getRow(row);
      subRow.getCell(1).value = '';
      subRow.getCell(2).value = 'SUB-TOTAL \u2014 SECTION ' + secNum + ': ' + secTitle;
      subRow.getCell(2).font = { name: 'Arial', size: 10, bold: true };
      subRow.getCell(3).value = '';
      subRow.getCell(4).value = '';
      subRow.getCell(5).value = '';
      subRow.getCell(6).value = { formula: 'SUM(F' + firstItemRow + ':F' + lastItemRow + ')' };
      subRow.getCell(7).value = { formula: 'SUM(G' + firstItemRow + ':G' + lastItemRow + ')' };
      subRow.getCell(8).value = { formula: 'SUM(H' + firstItemRow + ':H' + lastItemRow + ')' };
      subRow.getCell(9).value = '';
      
      for (var sc = 1; sc <= 9; sc++) {
        subRow.getCell(sc).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
        subRow.getCell(sc).border = allBorders;
        subRow.getCell(sc).font = subRow.getCell(sc).font || {};
        subRow.getCell(sc).font = { name: 'Arial', size: 10, bold: true };
        if (sc >= 5 && sc <= 8) subRow.getCell(sc).numFmt = currFmt;
      }
      subRow.height = 22;
      subtotalRows.push(row);
      row++;
    }

    // Blank row between sections
    row++;
  }

  // === SUMMARY ===
  row++;
  var sumHeaderRow = ws.getRow(row);
  ws.mergeCells('A' + row + ':I' + row);
  sumHeaderRow.getCell(1).value = 'PROJECT SUMMARY';
  sumHeaderRow.getCell(1).font = { name: 'Arial', size: 10, bold: true, color: { argb: '1B2A4A' } };
  sumHeaderRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
  sumHeaderRow.getCell(1).border = allBorders;
  row++;

  // Net total
  var netFormula = subtotalRows.length > 0 ? subtotalRows.map(function(r) { return 'H' + r; }).join('+') : '0';
  var netRow = ws.getRow(row);
  netRow.getCell(2).value = 'Net Construction Cost';
  netRow.getCell(2).font = { name: 'Arial', size: 10, bold: true };
  netRow.getCell(8).value = { formula: netFormula };
  netRow.getCell(8).numFmt = currFmt;
  netRow.getCell(8).font = { name: 'Arial', size: 10, bold: true };
  netRow.getCell(8).border = allBorders;
  var netRowNum = row;
  row++;

  // Contingency
  var contRow = ws.getRow(row);
  contRow.getCell(2).value = 'Contingency (' + contingencyPct + '%)';
  contRow.getCell(2).font = { name: 'Arial', size: 10 };
  contRow.getCell(8).value = { formula: 'H' + netRowNum + '*' + (contingencyPct / 100) };
  contRow.getCell(8).numFmt = currFmt;
  contRow.getCell(8).font = { name: 'Arial', size: 10 };
  contRow.getCell(8).border = allBorders;
  var contRowNum = row;
  row++;

  // OH&P
  var ohpRow = ws.getRow(row);
  ohpRow.getCell(2).value = 'Overheads & Profit (' + ohpPct + '%)';
  ohpRow.getCell(2).font = { name: 'Arial', size: 10 };
  ohpRow.getCell(8).value = { formula: 'H' + netRowNum + '*' + (ohpPct / 100) };
  ohpRow.getCell(8).numFmt = currFmt;
  ohpRow.getCell(8).font = { name: 'Arial', size: 10 };
  ohpRow.getCell(8).border = allBorders;
  var ohpRowNum = row;
  row++;

  // Grand total excl VAT
  var gtRow = ws.getRow(row);
  gtRow.getCell(2).value = 'TOTAL CONSTRUCTION COST (EXCL. VAT)';
  gtRow.getCell(2).font = { name: 'Arial', size: 11, bold: true, color: { argb: '1B2A4A' } };
  gtRow.getCell(8).value = { formula: 'H' + netRowNum + '+H' + contRowNum + '+H' + ohpRowNum };
  gtRow.getCell(8).numFmt = currFmt;
  gtRow.getCell(8).font = { name: 'Arial', size: 11, bold: true };
  for (var gc = 1; gc <= 9; gc++) {
    gtRow.getCell(gc).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    gtRow.getCell(gc).border = allBorders;
  }
  var gtRowNum = row;
  row++;

  // VAT
  var vatRow = ws.getRow(row);
  vatRow.getCell(2).value = 'VAT @ ' + vatRate + '%';
  vatRow.getCell(2).font = { name: 'Arial', size: 10 };
  vatRow.getCell(8).value = { formula: 'H' + gtRowNum + '*' + (vatRate / 100) };
  vatRow.getCell(8).numFmt = currFmt;
  vatRow.getCell(8).font = { name: 'Arial', size: 10 };
  vatRow.getCell(8).border = allBorders;
  var vatRowNum = row;
  row++;

  // Total incl VAT
  var inclRow = ws.getRow(row);
  inclRow.getCell(2).value = 'TOTAL CONSTRUCTION COST (INCL. VAT @ ' + vatRate + '%)';
  inclRow.getCell(2).font = { name: 'Arial', size: 11, bold: true, color: { argb: '1B2A4A' } };
  inclRow.getCell(8).value = { formula: 'H' + gtRowNum + '+H' + vatRowNum };
  inclRow.getCell(8).numFmt = currFmt;
  inclRow.getCell(8).font = { name: 'Arial', size: 11, bold: true };
  for (var ic = 1; ic <= 9; ic++) {
    inclRow.getCell(ic).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    inclRow.getCell(ic).border = allBorders;
  }
  row++;

  // Legend
  row++;
  ws.getRow(row).getCell(2).value = 'Rate Source Legend:';
  ws.getRow(row).getCell(2).font = { name: 'Arial', size: 9, bold: true };
  row++;
  ws.getRow(row).getCell(2).value = 'Verified = Client-confirmed rate';
  ws.getRow(row).getCell(2).font = { name: 'Arial', size: 9, color: { argb: 'FF059669' } };
  row++;
  ws.getRow(row).getCell(2).value = 'Emerging = Client rate, calibrating';
  ws.getRow(row).getCell(2).font = { name: 'Arial', size: 9, color: { argb: 'FFD97706' } };
  row++;
  ws.getRow(row).getCell(2).value = 'Generic = UK database rate';
  ws.getRow(row).getCell(2).font = { name: 'Arial', size: 9, color: { argb: 'FF64748B' } };

  // Freeze panes
  ws.views = [{ state: 'frozen', ySplit: headerRowNum, activeCell: 'A' + (headerRowNum + 1) }];

  // Footer
  ws.headerFooter.oddFooter = '&LThe AI QS - theaiqs.co.uk&RPage &P of &N';

  // Write buffer
  var buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

module.exports = { generateBOQExcel };
