/**
 * Builder Pack — parses the BOQ that the QS team produced and re-renders it
 * in the formats builders ask for: a trade summary, a materials-only schedule,
 * and a labour-only schedule. All three sit on tabs of one workbook so the
 * builder gets one clean download.
 *
 * Every output is marked TESTING — this whole flow is still in beta.
 *
 * The source BOQ layout is generated by server/boqGenerator.js:
 *   row 1   title (merged A:I)
 *   row 2   client/date (merged A:I)
 *   row 3   blank
 *   row 4   header row (Item, Description, Unit, Qty, Rate, Labour, Materials, Total, Source)
 *   row 5+  pattern of [section header (merged A:I), N item rows, sub-total row, blank, ...]
 *           then a PROJECT SUMMARY block at the bottom.
 *
 * We treat any merged-A:I row as a section break, any row with a numeric Qty (col 4)
 * as a line item, and we stop at the PROJECT SUMMARY block.
 */

const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');

// Convert "#RRGGBB" to ExcelJS argb ("FFRRGGBB"). Returns null if invalid.
function hexToArgb(hex) {
  if (typeof hex !== 'string') return null;
  const m = hex.replace('#', '').toUpperCase();
  if (!/^[0-9A-F]{6}$/.test(m)) return null;
  return 'FF' + m;
}

// Return a much lighter tint of a hex colour, used for section row banding.
// pct=0 returns the same colour; pct=0.85 is very pale.
function tintHex(hex, pct) {
  if (typeof hex !== 'string') return null;
  const h = hex.replace('#', '');
  if (h.length !== 6) return null;
  const num = parseInt(h, 16);
  let r = (num >> 16) & 0xff;
  let g = (num >> 8) & 0xff;
  let b = num & 0xff;
  r = Math.round(r + (255 - r) * pct);
  g = Math.round(g + (255 - g) * pct);
  b = Math.round(b + (255 - b) * pct);
  return '#' + [r, g, b].map((x) => x.toString(16).padStart(2, '0').toUpperCase()).join('');
}

// Per-template visual variants — controls heading font, section banding tint,
// and the accent bar style. Logo + colours come from the user's branding.
const TEMPLATES = {
  modern: {
    headingFont: 'Calibri',
    bodyFont: 'Calibri',
    sectionTintPct: 0.82,
    titleSize: 22,
    coverFlavour: 'gradient',
  },
  professional: {
    headingFont: 'Cambria',
    bodyFont: 'Calibri',
    sectionTintPct: 0.92, // nearly white, hairline borders
    titleSize: 20,
    coverFlavour: 'classic',
  },
  heritage: {
    headingFont: 'Cambria',
    bodyFont: 'Calibri',
    sectionTintPct: 0.88,
    titleSize: 22,
    coverFlavour: 'beige',
  },
  minimalist: {
    headingFont: 'Calibri',
    bodyFont: 'Calibri',
    sectionTintPct: 0.95,
    titleSize: 24,
    coverFlavour: 'minimal',
  },
};

function templateOpts(name) {
  return TEMPLATES[name] || TEMPLATES.modern;
}

// Try to embed the customer's logo onto a worksheet. Returns the image id (or null).
function tryEmbedLogo(wb, ws, logoPath, anchor) {
  if (!logoPath || !fs.existsSync(logoPath)) return null;
  try {
    const ext = path.extname(logoPath).toLowerCase().replace('.', '') || 'png';
    // ExcelJS supports png, jpeg, gif. Map jpg/webp/svg sensibly.
    let extension = ext;
    if (ext === 'jpg') extension = 'jpeg';
    if (ext === 'webp' || ext === 'svg') {
      // ExcelJS can't embed webp/svg directly — skip rather than fail the export.
      return null;
    }
    const id = wb.addImage({ filename: logoPath, extension });
    ws.addImage(id, anchor);
    return id;
  } catch (e) {
    return null;
  }
}

function cellText(cell) {
  if (cell == null) return '';
  const v = cell.value;
  if (v == null) return '';
  if (typeof v === 'string') return v;
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') {
    if (v.richText) return v.richText.map((r) => r.text).join('');
    if (v.formula && v.result != null) return String(v.result);
    if (v.text) return v.text;
  }
  return '';
}

function cellNumber(cell) {
  if (cell == null) return 0;
  const v = cell.value;
  if (typeof v === 'number') return v;
  if (typeof v === 'object' && v && typeof v.result === 'number') return v.result;
  return 0;
}

/**
 * Detect whether a row looks like a section / trade header. Real-world BOQs
 * use any of:
 *   - A merged-cells row (A:H or A:I or A:F …) with a label in col A
 *   - A coloured fill (the SECTION_BG light-blue) on col A or col B
 *   - A "1." / "1.1" / "A." numeric/letter prefix in col A or col B,
 *     with no numeric data in the rate / total columns
 *
 * The previous detector only matched a strict A:I merge — fine for BOQs
 * generated by this app, but BOQs from other generators or hand-edits got
 * dumped into a single GENERAL bucket.
 */
function looksLikeSectionRow(row, mergedRows) {
  const rowNumber = row.number;
  if (mergedRows.has(rowNumber)) return true;

  const a = cellText(row.getCell(1)).trim();
  const b = cellText(row.getCell(2)).trim();
  const text = a || b;
  if (!text) return false;

  // No numeric data in rate (5), labour (6), materials (7) or total (8) — section rows are label-only
  const hasNumbers =
    cellNumber(row.getCell(5)) > 0 ||
    cellNumber(row.getCell(6)) > 0 ||
    cellNumber(row.getCell(7)) > 0 ||
    cellNumber(row.getCell(8)) > 0;
  if (hasNumbers) return false;

  // Pattern: "1.", "1.2", "A.", "Section 1", "TRADE" all-caps with letters
  const numberedPrefix = /^\s*(\d+(?:\.\d+)*)[.)]?\s+\S/.test(text);
  const allCapsHeading = /^[A-Z][A-Z0-9 &/(),.\-]{4,}$/.test(text); // e.g. "PRELIMINARIES", "GROUNDWORKS & SUBSTRUCTURE"
  const hasFill = !!(
    (row.getCell(1).fill && row.getCell(1).fill.fgColor && row.getCell(1).fill.fgColor.argb &&
      row.getCell(1).fill.fgColor.argb !== 'FFFFFFFF') ||
    (row.getCell(2).fill && row.getCell(2).fill.fgColor && row.getCell(2).fill.fgColor.argb &&
      row.getCell(2).fill.fgColor.argb !== 'FFFFFFFF')
  );

  return numberedPrefix || allCapsHeading || hasFill;
}

function parseSectionLabel(text, fallbackIdx) {
  const m = text.match(/^\s*([\d]+(?:\.\d+)*)[.)]?\s+(.+)$/);
  if (m) return { number: m[1], title: m[2].trim() };
  return { number: String(fallbackIdx + 1), title: text.trim() };
}

/**
 * Parse a BOQ workbook and return the structured sections / items / totals.
 * Returns { sections: [{ number, title, items: [...], subtotal: { labour, materials, total } }], grand: { labour, materials, total } }
 */
async function parseBOQ(filePath) {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(filePath);
  const ws = wb.getWorksheet('BOQ') || wb.worksheets[0];
  if (!ws) throw new Error('BOQ worksheet not found');

  // Collect any row that has a merge anchored at column A, regardless of width.
  // Some BOQs use A:F, A:G, A:H etc.
  const mergedRows = new Set();
  for (const key of Object.keys(ws._merges || {})) {
    const m = key.match(/^A(\d+):[A-Z]+\1$/i);
    if (m) mergedRows.add(parseInt(m[1], 10));
  }

  // Detect which row holds the column headers ("Item", "Description", "Qty", "Rate"…)
  // so we can skip everything above it. Default to row 4 (matches our generator).
  let headerRow = 4;
  ws.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber > 8) return;
    const joined = [1, 2, 3, 4, 5, 6, 7, 8].map((c) => cellText(row.getCell(c)).toLowerCase()).join(' | ');
    if (joined.includes('description') && (joined.includes('qty') || joined.includes('quantity'))) {
      headerRow = rowNumber;
    }
  });

  const sections = [];
  let current = null;
  let stopped = false;

  ws.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (stopped) return;
    if (rowNumber <= headerRow) return;

    const a = cellText(row.getCell(1)).trim();
    const b = cellText(row.getCell(2)).trim();
    const upperA = a.toUpperCase();
    const upperB = b.toUpperCase();

    // Stop at the project summary block — that's QS-side, not item-level
    if (upperA.includes('PROJECT SUMMARY') || upperB.includes('PROJECT SUMMARY') ||
        upperA.includes('GRAND TOTAL') || upperB.includes('GRAND TOTAL')) {
      stopped = true;
      return;
    }

    // Sub-total row — typed as "SUB-TOTAL" or "Subtotal" in either col A or col B
    if (upperA.startsWith('SUB-TOTAL') || upperA.startsWith('SUBTOTAL') ||
        upperB.startsWith('SUB-TOTAL') || upperB.startsWith('SUBTOTAL')) {
      if (current) {
        current.subtotal = {
          labour: cellNumber(row.getCell(6)),
          materials: cellNumber(row.getCell(7)),
          total: cellNumber(row.getCell(8)),
        };
      }
      return;
    }

    // Section header detection (merge OR fill OR numbered/all-caps prefix)
    if (looksLikeSectionRow(row, mergedRows)) {
      const label = a || b;
      const { number, title } = parseSectionLabel(label, sections.length);
      // Avoid creating an empty section if we get two heading rows in a row
      // before any items — just update the current pointer.
      if (current && current.items.length === 0) {
        current.number = number;
        current.title = title;
      } else {
        current = { number, title, items: [], subtotal: { labour: 0, materials: 0, total: 0 } };
        sections.push(current);
      }
      return;
    }

    // Item row — must have a description and at least one numeric value.
    const qty = cellNumber(row.getCell(4));
    const rate = cellNumber(row.getCell(5));
    const labour = cellNumber(row.getCell(6));
    const materials = cellNumber(row.getCell(7));
    const total = cellNumber(row.getCell(8));
    const description = b;
    const unit = cellText(row.getCell(3)).trim();
    const itemRef = a;

    if (description && (qty > 0 || rate > 0 || labour > 0 || materials > 0 || total > 0)) {
      if (!current) {
        current = { number: '1', title: 'GENERAL', items: [], subtotal: { labour: 0, materials: 0, total: 0 } };
        sections.push(current);
      }
      current.items.push({ itemRef, description, unit, qty, rate, labour, materials, total });
    }
  });

  // Drop empty sections (a heading row with no items beneath it)
  const cleaned = sections.filter((s) => s.items.length > 0);

  // Backfill subtotals from items if missing
  for (const s of cleaned) {
    if (s.subtotal.total === 0 && s.items.length) {
      s.subtotal.labour = s.items.reduce((a, i) => a + (i.labour || 0), 0);
      s.subtotal.materials = s.items.reduce((a, i) => a + (i.materials || 0), 0);
      s.subtotal.total = s.items.reduce((a, i) => a + (i.total || 0), 0);
    }
  }

  const grand = cleaned.reduce(
    (acc, s) => ({
      labour: acc.labour + (s.subtotal.labour || 0),
      materials: acc.materials + (s.subtotal.materials || 0),
      total: acc.total + (s.subtotal.total || 0),
    }),
    { labour: 0, materials: 0, total: 0 }
  );

  return { sections: cleaned, grand };
}

/**
 * Generate a multi-tab "Builder Pack" workbook.
 *
 * opts:
 *   currency:        '£' | '€'  (default '£')
 *   builder_margin:  number     extra % the builder wants on top of the QS rate (default 0)
 *   materials_markup:number     extra % on materials only (default 0)
 *   project_name:    string
 *   client_name:     string
 */
async function generateBuilderPack(parsed, opts = {}) {
  const currency = opts.currency || '£';
  const builderMargin = parseFloat(opts.builder_margin) || 0;
  const materialsMarkup = parseFloat(opts.materials_markup) || 0;
  const projectName = opts.project_name || 'Project';
  const clientName = opts.client_name || 'Client';

  const labourMult = 1 + builderMargin / 100;
  const matMult = 1 + builderMargin / 100 + materialsMarkup / 100;

  const wb = new ExcelJS.Workbook();
  wb.creator = 'The AI QS — Builder Pack (TESTING)';
  wb.created = new Date();

  const NAVY = 'FF1B2A4A';
  const SECTION_BG = 'FFD6E4F0';
  const SUBTOTAL_BG = 'FFFFF2CC';
  const TESTING_BG = 'FFFEE2E2';
  const BORDER_COL = 'FFCBD5E1';
  const thin = { style: 'thin', color: { argb: BORDER_COL } };
  const allBorders = { top: thin, bottom: thin, left: thin, right: thin };
  const currFmt = '#,##0.00';

  function addTestingBanner(ws, lastCol = 'F') {
    ws.mergeCells('A1:' + lastCol + '1');
    const c = ws.getCell('A1');
    c.value = 'TESTING / BETA — Builder Pack output. Not for live commercial use without QS sign-off.';
    c.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFB91C1C' } };
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TESTING_BG } };
    c.alignment = { horizontal: 'center', vertical: 'middle' };
    ws.getRow(1).height = 22;
  }

  function titleBlock(ws, label, lastCol) {
    addTestingBanner(ws, lastCol);
    ws.mergeCells('A2:' + lastCol + '2');
    const t = ws.getCell('A2');
    t.value = label + ' — ' + projectName;
    t.font = { name: 'Arial', size: 14, bold: true, color: { argb: '1B2A4A' } };
    ws.getRow(2).height = 26;

    ws.mergeCells('A3:' + lastCol + '3');
    const i = ws.getCell('A3');
    i.value =
      'Client: ' + clientName +
      '  |  Date: ' + new Date().toLocaleDateString('en-GB') +
      (builderMargin ? '  |  Builder margin: +' + builderMargin + '%' : '') +
      (materialsMarkup ? '  |  Materials markup: +' + materialsMarkup + '%' : '');
    i.font = { name: 'Arial', size: 10, color: { argb: '64748B' } };
    ws.getRow(3).height = 18;
  }

  // ─── Tab 1: Trade Summary ─────────────────────────────────────────────────
  const ts = wb.addWorksheet('Trade Summary', {
    pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true, fitToWidth: 1 },
  });
  ts.columns = [
    { key: 'no', width: 6 },
    { key: 'trade', width: 42 },
    { key: 'labour', width: 16 },
    { key: 'materials', width: 16 },
    { key: 'total', width: 16 },
    { key: 'pct', width: 10 },
  ];
  titleBlock(ts, 'TRADE SUMMARY', 'F');

  const tsHdr = ts.getRow(5);
  tsHdr.values = ['#', 'Trade / Section', 'Labour (' + currency + ')', 'Materials (' + currency + ')', 'Total (' + currency + ')', '% of project'];
  for (let c = 1; c <= 6; c++) {
    const cell = tsHdr.getCell(c);
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  tsHdr.height = 24;

  let projectTotal = parsed.grand.total * labourMult; // approx; we recompute after applying materials markup separately
  projectTotal = parsed.sections.reduce(
    (acc, s) => acc + s.subtotal.labour * labourMult + s.subtotal.materials * matMult,
    0
  );

  let r = 6;
  parsed.sections.forEach((s, idx) => {
    const labour = s.subtotal.labour * labourMult;
    const materials = s.subtotal.materials * matMult;
    const total = labour + materials;
    const row = ts.getRow(r++);
    row.getCell(1).value = idx + 1;
    row.getCell(2).value = s.title;
    row.getCell(3).value = Math.round(labour * 100) / 100;
    row.getCell(4).value = Math.round(materials * 100) / 100;
    row.getCell(5).value = Math.round(total * 100) / 100;
    row.getCell(6).value = projectTotal > 0 ? total / projectTotal : 0;
    for (let c = 1; c <= 6; c++) {
      row.getCell(c).border = allBorders;
      row.getCell(c).font = { name: 'Arial', size: 10 };
      if (c >= 3 && c <= 5) row.getCell(c).numFmt = currFmt;
      if (c === 6) row.getCell(c).numFmt = '0.0%';
      if (c === 1 || c === 6) row.getCell(c).alignment = { horizontal: 'center' };
      if (c === 3 || c === 4 || c === 5) row.getCell(c).alignment = { horizontal: 'right' };
    }
  });

  // Grand total
  const gt = ts.getRow(r++);
  gt.getCell(2).value = 'GRAND TOTAL';
  gt.getCell(3).value = Math.round(parsed.grand.labour * labourMult * 100) / 100;
  gt.getCell(4).value = Math.round(parsed.grand.materials * matMult * 100) / 100;
  gt.getCell(5).value = Math.round(projectTotal * 100) / 100;
  gt.getCell(6).value = 1;
  for (let c = 1; c <= 6; c++) {
    gt.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    gt.getCell(c).border = allBorders;
    gt.getCell(c).font = { name: 'Arial', size: 11, bold: true };
    if (c >= 3 && c <= 5) gt.getCell(c).numFmt = currFmt;
    if (c === 6) gt.getCell(c).numFmt = '0.0%';
    if (c === 3 || c === 4 || c === 5) gt.getCell(c).alignment = { horizontal: 'right' };
  }

  ts.views = [{ state: 'frozen', ySplit: 5 }];

  // ─── Tab 2: Materials Schedule ────────────────────────────────────────────
  const ms = wb.addWorksheet('Materials Schedule', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  });
  ms.columns = [
    { key: 'item', width: 8 },
    { key: 'desc', width: 50 },
    { key: 'unit', width: 8 },
    { key: 'qty', width: 10 },
    { key: 'mat', width: 16 },
  ];
  titleBlock(ms, 'MATERIALS SCHEDULE', 'E');
  const msHdr = ms.getRow(5);
  msHdr.values = ['Item', 'Description', 'Unit', 'Qty', 'Materials (' + currency + ')'];
  for (let c = 1; c <= 5; c++) {
    const cell = msHdr.getCell(c);
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  msHdr.height = 24;

  let mr = 6;
  let materialsRunning = 0;
  parsed.sections.forEach((s) => {
    const itemsWithMat = s.items.filter((i) => (i.materials || 0) > 0);
    if (!itemsWithMat.length) return;
    // Section row
    const sec = ms.getRow(mr++);
    ms.mergeCells('A' + (mr - 1) + ':E' + (mr - 1));
    sec.getCell(1).value = s.title.toUpperCase();
    sec.getCell(1).font = { name: 'Arial', size: 10, bold: true, color: { argb: '1B2A4A' } };
    sec.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
    sec.getCell(1).border = allBorders;
    sec.height = 20;

    let sectionMat = 0;
    for (const it of itemsWithMat) {
      const matVal = it.materials * matMult;
      sectionMat += matVal;
      const row = ms.getRow(mr++);
      row.getCell(1).value = it.itemRef;
      row.getCell(2).value = it.description;
      row.getCell(3).value = it.unit;
      row.getCell(4).value = it.qty;
      row.getCell(5).value = Math.round(matVal * 100) / 100;
      for (let c = 1; c <= 5; c++) {
        row.getCell(c).border = allBorders;
        row.getCell(c).font = { name: 'Arial', size: 10 };
        if (c === 5) {
          row.getCell(c).numFmt = currFmt;
          row.getCell(c).alignment = { horizontal: 'right' };
        }
        if (c === 1 || c === 3) row.getCell(c).alignment = { horizontal: 'center' };
        if (c === 4) {
          row.getCell(c).numFmt = '#,##0.00';
          row.getCell(c).alignment = { horizontal: 'center' };
        }
        if (c === 2) row.getCell(c).alignment = { wrapText: true, vertical: 'top' };
      }
    }
    materialsRunning += sectionMat;

    const sub = ms.getRow(mr++);
    sub.getCell(2).value = 'Subtotal — ' + s.title;
    sub.getCell(5).value = Math.round(sectionMat * 100) / 100;
    for (let c = 1; c <= 5; c++) {
      sub.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
      sub.getCell(c).border = allBorders;
      sub.getCell(c).font = { name: 'Arial', size: 10, bold: true };
      if (c === 5) {
        sub.getCell(c).numFmt = currFmt;
        sub.getCell(c).alignment = { horizontal: 'right' };
      }
    }
  });

  // Materials grand total
  const matGT = ms.getRow(mr++);
  matGT.getCell(2).value = 'TOTAL MATERIALS';
  matGT.getCell(5).value = Math.round(materialsRunning * 100) / 100;
  for (let c = 1; c <= 5; c++) {
    matGT.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    matGT.getCell(c).border = allBorders;
    matGT.getCell(c).font = { name: 'Arial', size: 11, bold: true };
    if (c === 5) {
      matGT.getCell(c).numFmt = currFmt;
      matGT.getCell(c).alignment = { horizontal: 'right' };
    }
  }
  ms.views = [{ state: 'frozen', ySplit: 5 }];

  // ─── Tab 3: Labour Schedule ───────────────────────────────────────────────
  const ls = wb.addWorksheet('Labour Schedule', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  });
  ls.columns = [
    { key: 'item', width: 8 },
    { key: 'desc', width: 50 },
    { key: 'unit', width: 8 },
    { key: 'qty', width: 10 },
    { key: 'lab', width: 16 },
  ];
  titleBlock(ls, 'LABOUR SCHEDULE', 'E');
  const lsHdr = ls.getRow(5);
  lsHdr.values = ['Item', 'Description', 'Unit', 'Qty', 'Labour (' + currency + ')'];
  for (let c = 1; c <= 5; c++) {
    const cell = lsHdr.getCell(c);
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  lsHdr.height = 24;

  let lr = 6;
  let labourRunning = 0;
  parsed.sections.forEach((s) => {
    const itemsWithLab = s.items.filter((i) => (i.labour || 0) > 0);
    if (!itemsWithLab.length) return;
    const sec = ls.getRow(lr++);
    ls.mergeCells('A' + (lr - 1) + ':E' + (lr - 1));
    sec.getCell(1).value = s.title.toUpperCase();
    sec.getCell(1).font = { name: 'Arial', size: 10, bold: true, color: { argb: '1B2A4A' } };
    sec.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
    sec.getCell(1).border = allBorders;
    sec.height = 20;

    let sectionLab = 0;
    for (const it of itemsWithLab) {
      const labVal = it.labour * labourMult;
      sectionLab += labVal;
      const row = ls.getRow(lr++);
      row.getCell(1).value = it.itemRef;
      row.getCell(2).value = it.description;
      row.getCell(3).value = it.unit;
      row.getCell(4).value = it.qty;
      row.getCell(5).value = Math.round(labVal * 100) / 100;
      for (let c = 1; c <= 5; c++) {
        row.getCell(c).border = allBorders;
        row.getCell(c).font = { name: 'Arial', size: 10 };
        if (c === 5) {
          row.getCell(c).numFmt = currFmt;
          row.getCell(c).alignment = { horizontal: 'right' };
        }
        if (c === 1 || c === 3) row.getCell(c).alignment = { horizontal: 'center' };
        if (c === 4) {
          row.getCell(c).numFmt = '#,##0.00';
          row.getCell(c).alignment = { horizontal: 'center' };
        }
        if (c === 2) row.getCell(c).alignment = { wrapText: true, vertical: 'top' };
      }
    }
    labourRunning += sectionLab;

    const sub = ls.getRow(lr++);
    sub.getCell(2).value = 'Subtotal — ' + s.title;
    sub.getCell(5).value = Math.round(sectionLab * 100) / 100;
    for (let c = 1; c <= 5; c++) {
      sub.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
      sub.getCell(c).border = allBorders;
      sub.getCell(c).font = { name: 'Arial', size: 10, bold: true };
      if (c === 5) {
        sub.getCell(c).numFmt = currFmt;
        sub.getCell(c).alignment = { horizontal: 'right' };
      }
    }
  });

  const labGT = ls.getRow(lr++);
  labGT.getCell(2).value = 'TOTAL LABOUR';
  labGT.getCell(5).value = Math.round(labourRunning * 100) / 100;
  for (let c = 1; c <= 5; c++) {
    labGT.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    labGT.getCell(c).border = allBorders;
    labGT.getCell(c).font = { name: 'Arial', size: 11, bold: true };
    if (c === 5) {
      labGT.getCell(c).numFmt = currFmt;
      labGT.getCell(c).alignment = { horizontal: 'right' };
    }
  }
  ls.views = [{ state: 'frozen', ySplit: 5 }];

  // Footer on every tab
  for (const tab of [ts, ms, ls]) {
    tab.headerFooter.oddFooter =
      '&LThe AI QS — BUILDER PACK (TESTING)&RPage &P of &N';
  }

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Generate an upgraded "Client Copy" — per-trade OH&P, optional flat prelims,
 * optional day-rate / management-fee line, configurable rounding.
 *
 * opts:
 *   currency:        '£' | '€'
 *   contingency:     number  (% on construction net, default 0)
 *   default_ohp:     number  (% applied unless a per-trade override exists)
 *   vat:             number  (% on the post-OH&P, post-contingency total)
 *   per_trade_ohp:   { [tradeNumber: string]: number }   override OH&P per section
 *   prelims_amount:  number  (£ flat — appears as a separate summary line)
 *   prelims_pct:     number  (% of net — alternative to flat amount)
 *   day_rate:        { label: string, days: number, rate_per_day: number }
 *   rounding:        0 | 1 | 10 | 100  (round each item total to nearest)
 *   project_name, client_name
 */
async function generateClientCopyPro(parsed, opts = {}) {
  const currency = opts.currency || '£';
  const contingency = parseFloat(opts.contingency) || 0;
  const defaultOhp = parseFloat(opts.default_ohp) || 0;
  const vat = parseFloat(opts.vat) || 0;
  const perTradeOhp = opts.per_trade_ohp || {};
  const prelimsAmount = parseFloat(opts.prelims_amount) || 0;
  const prelimsPct = parseFloat(opts.prelims_pct) || 0;
  const rounding = [0, 1, 10, 100].includes(parseInt(opts.rounding, 10)) ? parseInt(opts.rounding, 10) : 0;
  const dayRate = opts.day_rate && opts.day_rate.days > 0 && opts.day_rate.rate_per_day > 0
    ? { label: opts.day_rate.label || 'Day-rate / management', days: parseFloat(opts.day_rate.days), rate_per_day: parseFloat(opts.day_rate.rate_per_day) }
    : null;
  const projectName = opts.project_name || 'Project';
  const clientName = opts.client_name || 'Client';

  function roundMoney(v) {
    if (!rounding || rounding < 1) return Math.round(v * 100) / 100;
    return Math.round(v / rounding) * rounding;
  }
  function ohpForSection(sectionNumber) {
    if (Object.prototype.hasOwnProperty.call(perTradeOhp, sectionNumber)) {
      const v = parseFloat(perTradeOhp[sectionNumber]);
      if (Number.isFinite(v)) return v;
    }
    return defaultOhp;
  }

  // ── Branding ─────────────────────────────────────────────────────────────
  const branding = opts.branding || {};
  const tmpl = templateOpts(branding.template);
  const PRIMARY = hexToArgb(branding.primary_colour) || 'FF1B2A4A';
  const ACCENT  = hexToArgb(branding.accent_colour)  || 'FFF59E0B';
  const SECTION_BG = hexToArgb(tintHex(branding.primary_colour || '#1B2A4A', tmpl.sectionTintPct)) || 'FFD6E4F0';
  const SUBTOTAL_BG = hexToArgb(tintHex(branding.accent_colour || '#F59E0B', 0.85)) || 'FFFFF2CC';
  const BORDER_COL = 'FFCBD5E1';
  const thin = { style: 'thin', color: { argb: BORDER_COL } };
  const allBorders = { top: thin, bottom: thin, left: thin, right: thin };
  const currFmt = '#,##0.00';
  const headingFont = tmpl.headingFont;
  const bodyFont = tmpl.bodyFont;

  const wb = new ExcelJS.Workbook();
  wb.creator = (branding.company_name || 'The AI QS') + ' — Client Copy';
  wb.created = new Date();

  // ── Cover sheet (first tab) ──────────────────────────────────────────────
  const cover = wb.addWorksheet('Cover', {
    pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true, fitToWidth: 1 },
  });
  cover.columns = [
    { width: 4 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 4 },
  ];

  // Logo block at top-left of the cover sheet
  if (tryEmbedLogo(wb, cover, branding.logo_path, { tl: { col: 1, row: 1 }, ext: { width: 160, height: 60 } })) {
    cover.getRow(1).height = 12;
    cover.getRow(2).height = 12;
    cover.getRow(3).height = 12;
    cover.getRow(4).height = 12;
  }

  // Company name block (top-right of the cover, opposite the logo)
  if (branding.company_name) {
    cover.mergeCells('C2:E2');
    const cn = cover.getCell('C2');
    cn.value = branding.company_name;
    cn.font = { name: headingFont, size: 14, bold: true, color: { argb: PRIMARY } };
    cn.alignment = { horizontal: 'right' };
  }
  if (branding.company_address) {
    cover.mergeCells('C3:E5');
    const ca = cover.getCell('C3');
    ca.value = branding.company_address;
    ca.font = { name: bodyFont, size: 9, color: { argb: 'FF64748B' } };
    ca.alignment = { horizontal: 'right', vertical: 'top', wrapText: true };
  }

  // Title block (rows 7-9)
  cover.getRow(7).height = 6;
  cover.mergeCells('B8:E8');
  const t1 = cover.getCell('B8');
  t1.value = 'BILL OF QUANTITIES';
  t1.font = { name: headingFont, size: 11, bold: true, color: { argb: ACCENT } };
  cover.mergeCells('B9:E10');
  const t2 = cover.getCell('B9');
  t2.value = projectName;
  t2.font = { name: headingFont, size: tmpl.titleSize, bold: true, color: { argb: PRIMARY } };
  t2.alignment = { vertical: 'top', wrapText: true };
  cover.getRow(9).height = 32;
  cover.getRow(10).height = 22;

  // Accent bar (row 11)
  cover.mergeCells('B11:E11');
  const bar = cover.getCell('B11');
  bar.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ACCENT } };
  cover.getRow(11).height = 6;

  // Meta panel (Prepared for / Date / etc.)
  function coverMeta(rowNum, label, value) {
    cover.getCell('B' + rowNum).value = label.toUpperCase();
    cover.getCell('B' + rowNum).font = { name: bodyFont, size: 8.5, bold: true, color: { argb: 'FF94A3B8' } };
    cover.mergeCells('C' + rowNum + ':E' + rowNum);
    cover.getCell('C' + rowNum).value = value;
    cover.getCell('C' + rowNum).font = { name: bodyFont, size: 11, bold: true, color: { argb: PRIMARY } };
  }
  cover.getRow(12).height = 14;
  coverMeta(13, 'Prepared for', clientName);
  coverMeta(14, 'Issued', new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }));
  // Total value placeholder — filled at the end once we know the real number.
  coverMeta(15, 'Total ex-VAT (provisional)', '—');

  // Footer (cover sheet)
  if (branding.footer_text) {
    cover.mergeCells('B28:E28');
    const f = cover.getCell('B28');
    f.value = branding.footer_text;
    f.font = { name: bodyFont, size: 9, italic: true, color: { argb: 'FF94A3B8' } };
    f.alignment = { horizontal: 'center' };
  }

  // ── Client Copy detail sheet ─────────────────────────────────────────────
  const ws = wb.addWorksheet('Client Copy', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  });

  ws.columns = [
    { key: 'item', width: 8 },
    { key: 'desc', width: 56 },
    { key: 'unit', width: 7 },
    { key: 'qty', width: 9 },
    { key: 'rate', width: 12 },
    { key: 'total', width: 14 },
  ];

  // Title block (with optional logo on the right)
  ws.mergeCells('A1:F1');
  ws.getCell('A1').value = 'Bill of Quantities — CLIENT COPY — ' + projectName;
  ws.getCell('A1').font = { name: headingFont, size: 14, bold: true, color: { argb: PRIMARY } };
  ws.getRow(1).height = 28;

  ws.mergeCells('A2:F2');
  ws.getCell('A2').value =
    'Client: ' + clientName + '  |  Date: ' + new Date().toLocaleDateString('en-GB')
    + (branding.company_name ? '  |  Issued by: ' + branding.company_name : '');
  ws.getCell('A2').font = { name: bodyFont, size: 10, color: { argb: 'FF64748B' } };

  // Accent strip across row 3
  ws.mergeCells('A3:F3');
  ws.getCell('A3').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ACCENT } };
  ws.getRow(3).height = 4;

  // Header row
  let r = 4;
  const hdr = ws.getRow(r);
  hdr.values = ['Item', 'Description', 'Unit', 'Qty', 'Rate (' + currency + ')', 'Total (' + currency + ')'];
  for (let c = 1; c <= 6; c++) {
    const cell = hdr.getCell(c);
    cell.font = { name: headingFont, size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PRIMARY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  hdr.height = 24;
  r++;

  // Per-section item rows. Each section has its own OH&P; line totals are
  // (labour + materials) × (1 + ohp/100), rounded as configured.
  const sectionTotals = []; // post-OH&P per section
  parsed.sections.forEach((s, idx) => {
    const sectionOhp = ohpForSection(s.number);
    const sectionMult = 1 + sectionOhp / 100;

    // Section header
    const sec = ws.getRow(r);
    ws.mergeCells('A' + r + ':F' + r);
    sec.getCell(1).value = s.number + '. ' + s.title.toUpperCase() +
      (sectionOhp !== defaultOhp ? '   (OH&P ' + sectionOhp + '%)' : '');
    sec.getCell(1).font = { name: headingFont, size: 10.5, bold: true, color: { argb: PRIMARY } };
    sec.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
    sec.getCell(1).border = allBorders;
    sec.height = 22;
    r++;

    let sectionTotal = 0;
    for (const it of s.items) {
      const baseLineTotal = (it.labour || 0) + (it.materials || 0) || (it.total || 0);
      const upliftedTotal = roundMoney(baseLineTotal * sectionMult);
      sectionTotal += upliftedTotal;
      const upliftedRate = it.qty > 0 ? upliftedTotal / it.qty : (it.rate || 0) * sectionMult;

      const row = ws.getRow(r);
      row.getCell(1).value = it.itemRef || '';
      row.getCell(2).value = it.description;
      row.getCell(3).value = it.unit;
      row.getCell(4).value = it.qty;
      row.getCell(5).value = Math.round(upliftedRate * 100) / 100;
      row.getCell(6).value = upliftedTotal;
      for (let c = 1; c <= 6; c++) {
        row.getCell(c).border = allBorders;
        row.getCell(c).font = { name: 'Arial', size: 10 };
      }
      row.getCell(2).alignment = { wrapText: true, vertical: 'top' };
      row.getCell(4).numFmt = '#,##0.00';
      row.getCell(5).numFmt = currFmt;
      row.getCell(6).numFmt = currFmt;
      row.getCell(5).alignment = { horizontal: 'right' };
      row.getCell(6).alignment = { horizontal: 'right' };
      r++;
    }

    // Section subtotal
    const sub = ws.getRow(r);
    sub.getCell(2).value = 'Sub-total — ' + s.title;
    sub.getCell(6).value = sectionTotal;
    for (let c = 1; c <= 6; c++) {
      sub.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
      sub.getCell(c).border = allBorders;
      sub.getCell(c).font = { name: 'Arial', size: 10, bold: true };
      if (c === 6) {
        sub.getCell(c).numFmt = currFmt;
        sub.getCell(c).alignment = { horizontal: 'right' };
      }
    }
    r++;
    r++; // blank
    sectionTotals.push({ section: s, total: sectionTotal });
  });

  // ── Summary block ──────────────────────────────────────────────────────
  const netConstruction = sectionTotals.reduce((a, x) => a + x.total, 0);

  const sumHdr = ws.getRow(r);
  ws.mergeCells('A' + r + ':F' + r);
  sumHdr.getCell(1).value = 'PROJECT SUMMARY';
  sumHdr.getCell(1).font = { name: headingFont, size: 11, bold: true, color: { argb: PRIMARY } };
  sumHdr.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
  sumHdr.getCell(1).border = allBorders;
  r++;

  function addSummaryLine(label, value, opt = {}) {
    const row = ws.getRow(r++);
    row.getCell(2).value = label;
    row.getCell(2).font = { name: 'Arial', size: 10, bold: !!opt.bold };
    row.getCell(6).value = value;
    row.getCell(6).numFmt = currFmt;
    row.getCell(6).font = { name: 'Arial', size: 10, bold: !!opt.bold };
    row.getCell(6).border = allBorders;
    row.getCell(6).alignment = { horizontal: 'right' };
    if (opt.fill) {
      for (let c = 1; c <= 6; c++) {
        row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
        row.getCell(c).border = allBorders;
      }
    }
    return row;
  }

  addSummaryLine('Net construction cost (incl. trade OH&P)', netConstruction);

  let runningTotal = netConstruction;

  if (prelimsAmount > 0) {
    addSummaryLine('Preliminaries (flat)', prelimsAmount);
    runningTotal += prelimsAmount;
  }
  if (prelimsPct > 0) {
    const v = netConstruction * (prelimsPct / 100);
    addSummaryLine('Preliminaries (' + prelimsPct + '% of net)', v);
    runningTotal += v;
  }
  if (dayRate) {
    const v = dayRate.days * dayRate.rate_per_day;
    addSummaryLine(dayRate.label + ' (' + dayRate.days + ' day' + (dayRate.days === 1 ? '' : 's') + ' @ ' + currency + dayRate.rate_per_day + ')', v);
    runningTotal += v;
  }
  if (contingency > 0) {
    const v = netConstruction * (contingency / 100);
    addSummaryLine('Contingency (' + contingency + '% of net)', v);
    runningTotal += v;
  }

  const exVat = runningTotal;
  addSummaryLine('TOTAL (EXCL. VAT)', exVat, { bold: true, fill: true });

  if (vat > 0) {
    const vatVal = exVat * (vat / 100);
    addSummaryLine('VAT @ ' + vat + '%', vatVal);
    addSummaryLine('TOTAL (INCL. VAT)', exVat + vatVal, { bold: true, fill: true });
  }

  // Footer note
  r++;
  const note = ws.getRow(r);
  note.getCell(2).value =
    'This document is prepared for client use. Rates are final and inclusive of overheads, profit'
    + (contingency > 0 ? ', contingency' : '')
    + (vat > 0 ? ' and VAT' : '')
    + '. No contractor margin is shown separately.';
  note.getCell(2).font = { name: bodyFont, size: 9, italic: true, color: { argb: 'FF888888' } };

  ws.views = [{ state: 'frozen', ySplit: 4, activeCell: 'A5' }];
  const footerLeft = branding.footer_text || branding.company_name || 'The AI QS';
  ws.headerFooter.oddFooter = '&L' + footerLeft + ' — CLIENT COPY&RPage &P of &N';

  // Now that we know the headline number, fill in the cover sheet's total
  const totalCell = cover.getCell('C15');
  const symFmt = (currency === '€' ? '€' : '£');
  totalCell.value = symFmt + Math.round(exVat).toLocaleString('en-GB');

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

module.exports = { parseBOQ, generateBuilderPack, generateClientCopyPro };
