/**
 * Builder Pack — parses the BOQ that the QS team produced and re-renders it
 * in the formats builders ask for: a trade summary, a materials-only schedule,
 * and a labour-only schedule. All three sit on tabs of one workbook so the
 * builder gets one clean download.
 *
 * Every output is marked TESTING — this whole flow is still in beta.
 *
 * The source BOQ layout is generated by server/boqGenerator.js:
 *   row 1   title (merged A:I)
 *   row 2   client/date (merged A:I)
 *   row 3   blank
 *   row 4   header row (Item, Description, Unit, Qty, Rate, Labour, Materials, Total, Source)
 *   row 5+  pattern of [section header (merged A:I), N item rows, sub-total row, blank, ...]
 *           then a PROJECT SUMMARY block at the bottom.
 *
 * We treat any merged-A:I row as a section break, any row with a numeric Qty (col 4)
 * as a line item, and we stop at the PROJECT SUMMARY block.
 */

const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');
// Scrub XML-illegal characters out of any data-derived text before it reaches a
// cell. BOQ descriptions scraped from PDFs occasionally carry Unicode
// non-characters / lone surrogates that ExcelJS writes verbatim, which makes
// Excel reject the whole workbook ("We found a problem with some content").
const { sanitizeXmlText, writeXlsxBuffer } = require('./docTemplates');

// Convert "#RRGGBB" to ExcelJS argb ("FFRRGGBB"). Returns null if invalid.
function hexToArgb(hex) {
  if (typeof hex !== 'string') return null;
  const m = hex.replace('#', '').toUpperCase();
  if (!/^[0-9A-F]{6}$/.test(m)) return null;
  return 'FF' + m;
}

// Return a much lighter tint of a hex colour, used for section row banding.
// pct=0 returns the same colour; pct=0.85 is very pale.
function tintHex(hex, pct) {
  if (typeof hex !== 'string') return null;
  const h = hex.replace('#', '');
  if (h.length !== 6) return null;
  const num = parseInt(h, 16);
  let r = (num >> 16) & 0xff;
  let g = (num >> 8) & 0xff;
  let b = num & 0xff;
  r = Math.round(r + (255 - r) * pct);
  g = Math.round(g + (255 - g) * pct);
  b = Math.round(b + (255 - b) * pct);
  return '#' + [r, g, b].map((x) => x.toString(16).padStart(2, '0').toUpperCase()).join('');
}

// Per-template visual variants — controls heading font, section banding tint,
// and the accent bar style. Logo + colours come from the user's branding.
const TEMPLATES = {
  modern: {
    headingFont: 'Calibri',
    bodyFont: 'Calibri',
    sectionTintPct: 0.82,
    titleSize: 22,
    coverFlavour: 'gradient',
  },
  professional: {
    headingFont: 'Cambria',
    bodyFont: 'Calibri',
    sectionTintPct: 0.92, // nearly white, hairline borders
    titleSize: 20,
    coverFlavour: 'classic',
  },
  heritage: {
    headingFont: 'Cambria',
    bodyFont: 'Calibri',
    sectionTintPct: 0.88,
    titleSize: 22,
    coverFlavour: 'beige',
  },
  minimalist: {
    headingFont: 'Calibri',
    bodyFont: 'Calibri',
    sectionTintPct: 0.95,
    titleSize: 24,
    coverFlavour: 'minimal',
  },
};

function templateOpts(name) {
  return TEMPLATES[name] || TEMPLATES.modern;
}

// Try to embed the customer's logo onto a worksheet. Returns the image id (or null).
function tryEmbedLogo(wb, ws, logoPath, anchor) {
  if (!logoPath || !fs.existsSync(logoPath)) return null;
  try {
    const ext = path.extname(logoPath).toLowerCase().replace('.', '') || 'png';
    // ExcelJS supports png, jpeg, gif. Map jpg/webp/svg sensibly.
    let extension = ext;
    if (ext === 'jpg') extension = 'jpeg';
    if (ext === 'webp' || ext === 'svg') {
      // ExcelJS can't embed webp/svg directly — skip rather than fail the export.
      return null;
    }
    const id = wb.addImage({ filename: logoPath, extension });
    ws.addImage(id, anchor);
    return id;
  } catch (e) {
    return null;
  }
}

function cellText(cell) {
  if (cell == null) return '';
  const v = cell.value;
  if (v == null) return '';
  if (typeof v === 'string') return v;
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') {
    if (v.richText) return v.richText.map((r) => r.text).join('');
    if (v.formula && v.result != null) return String(v.result);
    if (v.text) return v.text;
  }
  return '';
}

function cellNumber(cell) {
  if (cell == null) return 0;
  const v = cell.value;
  if (typeof v === 'number') return v;
  if (typeof v === 'object' && v && typeof v.result === 'number') return v.result;
  return 0;
}

// Short codes that legitimately live in the "Unit" column. Used to tell a real
// unit ("m2", "nr", "item") apart from a line description that has been shifted
// into the unit column by a mis-aligned source BOQ.
const UNIT_TOKENS = new Set([
  'm', 'm2', 'm²', 'm3', 'm³', 'mm', 'lm', 'linm',
  'nr', 'no', 'no.', 'ea', 'each', 'item', 'items', 'set', 'sets',
  'pair', 'sum', 'ls', 'l/s', 'kg', 't', 'tonne', 'tonnes',
  'hr', 'hrs', 'day', 'days', 'wk', 'week', 'weeks', '%', 'visit',
  'pc', 'pcs', 'roll', 'sheet', 'coat', 'bag', 'load', 'unit',
]);
const BARE_NUMBER = /^\d+(?:\.\d+)?$/;

function looksLikeUnit(s) {
  const t = String(s || '').trim().toLowerCase();
  if (!t) return false;
  if (UNIT_TOKENS.has(t)) return true;
  // Short, single-token, no spaces — treat as a (possibly bespoke) unit code.
  return t.length <= 4 && !/\s/.test(t);
}

// True when a string reads like a line-item description rather than a unit: it
// contains letters and is either multi-word or comfortably longer than a unit
// code, and isn't itself a known unit token.
function looksLikeDescriptionText(s) {
  const t = String(s || '').trim();
  if (!t || looksLikeUnit(t)) return false;
  if (!/[A-Za-z]/.test(t)) return false;
  return /\s/.test(t) || t.length > 12;
}

/**
 * Detect whether a row looks like a section / trade header. Real-world BOQs
 * use any of:
 *   - A merged-cells row (A:H or A:I or A:F …) with a label in col A
 *   - A coloured fill (the SECTION_BG light-blue) on col A or col B
 *   - A "1." / "1.1" / "A." numeric/letter prefix in col A or col B,
 *     with no numeric data in the rate / total columns
 *
 * The previous detector only matched a strict A:I merge — fine for BOQs
 * generated by this app, but BOQs from other generators or hand-edits got
 * dumped into a single GENERAL bucket.
 */
function looksLikeSectionRow(row, mergedRows) {
  const rowNumber = row.number;
  if (mergedRows.has(rowNumber)) return true;

  const a = cellText(row.getCell(1)).trim();
  const b = cellText(row.getCell(2)).trim();
  const text = a || b;
  if (!text) return false;

  // No numeric data in rate (5), labour (6), materials (7) or total (8) — section rows are label-only
  const hasNumbers =
    cellNumber(row.getCell(5)) > 0 ||
    cellNumber(row.getCell(6)) > 0 ||
    cellNumber(row.getCell(7)) > 0 ||
    cellNumber(row.getCell(8)) > 0;
  if (hasNumbers) return false;

  // Pattern: "1.", "1.2", "A.", "Section 1", "TRADE" all-caps with letters
  const numberedPrefix = /^\s*(\d+(?:\.\d+)*)[.)]?\s+\S/.test(text);
  const allCapsHeading = /^[A-Z][A-Z0-9 &/(),.\-]{4,}$/.test(text); // e.g. "PRELIMINARIES", "GROUNDWORKS & SUBSTRUCTURE"
  const hasFill = !!(
    (row.getCell(1).fill && row.getCell(1).fill.fgColor && row.getCell(1).fill.fgColor.argb &&
      row.getCell(1).fill.fgColor.argb !== 'FFFFFFFF') ||
    (row.getCell(2).fill && row.getCell(2).fill.fgColor && row.getCell(2).fill.fgColor.argb &&
      row.getCell(2).fill.fgColor.argb !== 'FFFFFFFF')
  );

  return numberedPrefix || allCapsHeading || hasFill;
}

function parseSectionLabel(text, fallbackIdx) {
  const m = text.match(/^\s*([\d]+(?:\.\d+)*)[.)]?\s+(.+)$/);
  if (m) return { number: m[1], title: m[2].trim() };
  return { number: String(fallbackIdx + 1), title: text.trim() };
}

/**
 * Parse a BOQ workbook and return the structured sections / items / totals.
 * Returns { sections: [{ number, title, items: [...], subtotal: { labour, materials, total } }], grand: { labour, materials, total } }
 */
async function parseBOQ(filePath) {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(filePath);
  const ws = wb.getWorksheet('BOQ') || wb.worksheets[0];
  if (!ws) throw new Error('BOQ worksheet not found');

  // Collect any row that has a merge anchored at column A, regardless of width.
  // Some BOQs use A:F, A:G, A:H etc. Depending on how the file was produced,
  // exceljs keys merges either by range ("A30:G30") or by anchor alone ("A30").
  const mergedRows = new Set();
  for (const key of Object.keys(ws._merges || {})) {
    const m = key.match(/^A(\d+)(?::[A-Z]+\1)?$/i);
    if (m) mergedRows.add(parseInt(m[1], 10));
  }

  // Detect which row holds the column headers ("Item", "Description", "Qty", "Rate"…)
  // so we can skip everything above it. Default to row 4 (matches our generator).
  // Scans the top 30 rows so a tall branded hero block on the BOQ tab is fine.
  let headerRow = 4;
  ws.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber > 30) return;
    const joined = [1, 2, 3, 4, 5, 6, 7, 8].map((c) => cellText(row.getCell(c)).toLowerCase()).join(' | ');
    if (joined.includes('description') && (joined.includes('qty') || joined.includes('quantity'))) {
      headerRow = rowNumber;
    }
  });

  const sections = [];
  let current = null;
  let stopped = false;
  // Summary adders printed at the bottom of the source document (OH&P,
  // contingency, VAT). Captured so a client copy can default to the same
  // bottom line as the BOQ it came from.
  const sourceSummary = { ohp_pct: null, ohp_sections: null, overhead_pct: null, profit_pct: null, contingency_pct: null, vat_pct: null };

  ws.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber <= headerRow) return;

    const a = cellText(row.getCell(1)).trim();
    const b = cellText(row.getCell(2)).trim();
    const upperA = a.toUpperCase();
    const upperB = b.toUpperCase();

    // Source summary lines — may sit beyond the stop marker, so detect them
    // before the stopped check. Guard: a real summary line has no unit/qty,
    // just a label and a value. Merged label rows mirror their text into every
    // column, so a unit cell that just repeats the label doesn't count.
    const upperLabel = (upperA || upperB);
    const unitText = cellText(row.getCell(3)).trim();
    const mirrored = !!unitText && unitText === (a || b);
    const hasUnitOrQty = !mirrored && (!!unitText || cellNumber(row.getCell(4)) > 0);
    if (!hasUnitOrQty && cellNumber(row.getCell(8)) > 0) {
      let m;
      if ((m = upperLabel.match(/^OVERHEADS\s*(?:&|AND)\s*PROFIT\D*?([\d.]+)\s*%/))) {
        sourceSummary.ohp_pct = parseFloat(m[1]);
        const sc = upperLabel.match(/SECTIONS?\s*([\d.]+)\s*[–—-]\s*([\d.]+)/);
        if (sc) sourceSummary.ohp_sections = [parseFloat(sc[1]), parseFloat(sc[2])];
        return;
      }
      // Tender summaries that print overhead and profit on separate lines
      // (profit usually "applied to Net + Overhead"). Captured so the client
      // copy can reproduce the same compounded bottom line.
      if ((m = upperLabel.match(/^OVERHEAD\b(?!S?\s*(?:&|AND)\s*PROFIT)\D*?([\d.]+)\s*%/))) {
        sourceSummary.overhead_pct = parseFloat(m[1]);
        return;
      }
      if ((m = upperLabel.match(/^PROFIT\b\D*?([\d.]+)\s*%/))) {
        sourceSummary.profit_pct = parseFloat(m[1]);
        return;
      }
      if ((m = upperLabel.match(/^CONTINGENCY\D*?([\d.]+)\s*%/))) {
        sourceSummary.contingency_pct = parseFloat(m[1]);
        return;
      }
      if ((m = upperLabel.match(/^VAT\s*@?\s*([\d.]+)\s*%/))) {
        sourceSummary.vat_pct = parseFloat(m[1]);
        return;
      }
    }

    if (stopped) return;

    // Section carry-down rows ("PRELIMINARIES — TO COLLECTION") repeat the
    // section total — skipping them stops the total being counted as an item.
    // The recomputed subtotal from the items matches the carried figure.
    if (upperLabel.includes('TO COLLECTION')) return;

    // Stop at the summary block — that's QS-side, not item-level
    if (upperA.includes('PROJECT SUMMARY') || upperB.includes('PROJECT SUMMARY') ||
        upperLabel.includes('SUMMARY OF TOTALS') ||
        upperA.includes('GRAND TOTAL') || upperB.includes('GRAND TOTAL') ||
        upperLabel.includes('COLLECTION & SUMMARY') ||
        upperLabel.startsWith('NET MEASURED WORKS') ||
        upperLabel.startsWith('TOTAL EXCLUDING VAT') || upperLabel.startsWith('TOTAL EXCL') ||
        upperLabel.startsWith('NET TOTAL') || upperLabel.includes('TENDER SUM')) {
      stopped = true;
      return;
    }

    // Sub-total row — typed as "SUB-TOTAL" or "Subtotal" in either col A or col B
    if (upperA.startsWith('SUB-TOTAL') || upperA.startsWith('SUBTOTAL') ||
        upperB.startsWith('SUB-TOTAL') || upperB.startsWith('SUBTOTAL')) {
      if (current) {
        current.subtotal = {
          labour: cellNumber(row.getCell(6)),
          materials: cellNumber(row.getCell(7)),
          total: cellNumber(row.getCell(8)),
        };
      }
      return;
    }

    // Section header detection (merge OR fill OR numbered/all-caps prefix)
    if (looksLikeSectionRow(row, mergedRows)) {
      const label = a || b;
      const { number, title } = parseSectionLabel(label, sections.length);
      // Avoid creating an empty section if we get two heading rows in a row
      // before any items — just update the current pointer.
      if (current && current.items.length === 0) {
        current.number = number;
        current.title = title;
      } else {
        current = { number, title, items: [], subtotal: { labour: 0, materials: 0, total: 0 } };
        sections.push(current);
      }
      return;
    }

    // Item row — must have a description and at least one numeric value.
    const qty = cellNumber(row.getCell(4));
    const rate = cellNumber(row.getCell(5));
    const labour = cellNumber(row.getCell(6));
    const materials = cellNumber(row.getCell(7));
    const total = cellNumber(row.getCell(8));
    let description = b;
    let unit = cellText(row.getCell(3)).trim();
    let itemRef = a;

    // Repair a one-column data shift seen in some delivered BOQs: the line
    // description lands in the Unit column while the Description column holds a
    // bare item number (or is blank). Detect it unambiguously — the "unit" cell
    // reads like prose and the "description" cell is empty or just a number —
    // and move the text back into Description (promoting a stray number into the
    // item ref). A correctly-aligned row (real prose in Description, a unit code
    // like "m2"/"nr" in Unit) never matches, so this is safe for well-formed
    // files and self-heals already-stored BOQs on the next read/export.
    if (looksLikeDescriptionText(unit) && (!description || BARE_NUMBER.test(description))) {
      if (!itemRef && BARE_NUMBER.test(description)) itemRef = description;
      description = unit;
      unit = '';
    }

    if (description && (qty > 0 || rate > 0 || labour > 0 || materials > 0 || total > 0)) {
      if (!current) {
        current = { number: '1', title: 'GENERAL', items: [], subtotal: { labour: 0, materials: 0, total: 0 } };
        sections.push(current);
      }
      current.items.push({ itemRef, description, unit, qty, rate, labour, materials, total });
    }
  });

  // Drop empty sections (a heading row with no items beneath it)
  const cleaned = sections.filter((s) => s.items.length > 0);

  // Normalise labour/materials to LINE totals. Two shapes exist in the wild:
  // the chat generator writes line totals (Total = Labour + Materials), while
  // QS-delivered BOQs write per-unit rates (Total = Rate × Qty, with Labour and
  // Materials also per unit). The file's own Total column is the ground truth,
  // so use it to tell the shapes apart line by line.
  const round2 = (v) => Math.round(v * 100) / 100;
  for (const s of cleaned) {
    for (const it of s.items) {
      const lm = (it.labour || 0) + (it.materials || 0);
      const tol = Math.max((it.total || 0) * 0.01, 0.51);
      if (it.total > 0 && lm > 0 && Math.abs(it.total - lm) > tol) {
        if (it.qty > 0 && Math.abs(it.total - lm * it.qty) <= tol) {
          // Per-unit shape: scale up by quantity
          it.labour = round2((it.labour || 0) * it.qty);
          it.materials = round2((it.materials || 0) * it.qty);
        } else {
          // Neither shape matches — trust Total, keep the labour/materials split
          it.labour = round2(it.total * ((it.labour || 0) / lm));
          it.materials = round2(it.total * ((it.materials || 0) / lm));
        }
      } else if (!(it.total > 0)) {
        it.total = lm > 0 ? round2(lm) : round2((it.rate || 0) * (it.qty || 0));
      }
    }
    // Recompute subtotals from the normalised items so they always agree
    s.subtotal.labour = s.items.reduce((a, i) => a + (i.labour || 0), 0);
    s.subtotal.materials = s.items.reduce((a, i) => a + (i.materials || 0), 0);
    s.subtotal.total = s.items.reduce((a, i) => a + (i.total || 0), 0);
  }

  const grand = cleaned.reduce(
    (acc, s) => ({
      labour: acc.labour + (s.subtotal.labour || 0),
      materials: acc.materials + (s.subtotal.materials || 0),
      total: acc.total + (s.subtotal.total || 0),
    }),
    { labour: 0, materials: 0, total: 0 }
  );

  return { sections: cleaned, grand, source_summary: sourceSummary };
}

/**
 * Generate a multi-tab "Builder Pack" workbook.
 *
 * opts:
 *   currency:        '£' | '€'  (default '£')
 *   builder_margin:  number     extra % the builder wants on top of the QS rate (default 0)
 *   materials_markup:number     extra % on materials only (default 0)
 *   project_name:    string
 *   client_name:     string
 */
async function generateBuilderPack(parsed, opts = {}) {
  const currency = opts.currency || '£';
  const builderMargin = parseFloat(opts.builder_margin) || 0;
  const materialsMarkup = parseFloat(opts.materials_markup) || 0;
  const projectName = sanitizeXmlText(opts.project_name || 'Project');
  const clientName = sanitizeXmlText(opts.client_name || 'Client');

  const labourMult = 1 + builderMargin / 100;
  const matMult = 1 + builderMargin / 100 + materialsMarkup / 100;

  const wb = new ExcelJS.Workbook();
  wb.creator = 'The AI QS — Builder Pack (TESTING)';
  wb.created = new Date();

  const NAVY = 'FF1B2A4A';
  const SECTION_BG = 'FFD6E4F0';
  const SUBTOTAL_BG = 'FFFFF2CC';
  const TESTING_BG = 'FFFEE2E2';
  const BORDER_COL = 'FFCBD5E1';
  const thin = { style: 'thin', color: { argb: BORDER_COL } };
  const allBorders = { top: thin, bottom: thin, left: thin, right: thin };
  const currFmt = '#,##0.00';

  function addTestingBanner(ws, lastCol = 'F') {
    ws.mergeCells('A1:' + lastCol + '1');
    const c = ws.getCell('A1');
    c.value = 'TESTING / BETA — Builder Pack output. Not for live commercial use without QS sign-off.';
    c.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFB91C1C' } };
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TESTING_BG } };
    c.alignment = { horizontal: 'center', vertical: 'middle' };
    ws.getRow(1).height = 22;
  }

  function titleBlock(ws, label, lastCol) {
    addTestingBanner(ws, lastCol);
    ws.mergeCells('A2:' + lastCol + '2');
    const t = ws.getCell('A2');
    t.value = label + ' — ' + projectName;
    t.font = { name: 'Arial', size: 14, bold: true, color: { argb: '1B2A4A' } };
    ws.getRow(2).height = 26;

    ws.mergeCells('A3:' + lastCol + '3');
    const i = ws.getCell('A3');
    i.value =
      'Client: ' + clientName +
      '  |  Date: ' + new Date().toLocaleDateString('en-GB') +
      (builderMargin ? '  |  Builder margin: +' + builderMargin + '%' : '') +
      (materialsMarkup ? '  |  Materials markup: +' + materialsMarkup + '%' : '');
    i.font = { name: 'Arial', size: 10, color: { argb: '64748B' } };
    ws.getRow(3).height = 18;
  }

  // ─── Tab 1: Trade Summary ─────────────────────────────────────────────────
  const ts = wb.addWorksheet('Trade Summary', {
    pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true, fitToWidth: 1 },
  });
  ts.columns = [
    { key: 'no', width: 6 },
    { key: 'trade', width: 42 },
    { key: 'labour', width: 16 },
    { key: 'materials', width: 16 },
    { key: 'total', width: 16 },
    { key: 'pct', width: 10 },
  ];
  titleBlock(ts, 'TRADE SUMMARY', 'F');

  const tsHdr = ts.getRow(5);
  tsHdr.values = ['#', 'Trade / Section', 'Labour (' + currency + ')', 'Materials (' + currency + ')', 'Total (' + currency + ')', '% of project'];
  for (let c = 1; c <= 6; c++) {
    const cell = tsHdr.getCell(c);
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  tsHdr.height = 24;

  let projectTotal = parsed.grand.total * labourMult; // approx; we recompute after applying materials markup separately
  projectTotal = parsed.sections.reduce(
    (acc, s) => acc + s.subtotal.labour * labourMult + s.subtotal.materials * matMult,
    0
  );

  let r = 6;
  parsed.sections.forEach((s, idx) => {
    const labour = s.subtotal.labour * labourMult;
    const materials = s.subtotal.materials * matMult;
    const total = labour + materials;
    const row = ts.getRow(r++);
    row.getCell(1).value = idx + 1;
    row.getCell(2).value = sanitizeXmlText(s.title);
    row.getCell(3).value = Math.round(labour * 100) / 100;
    row.getCell(4).value = Math.round(materials * 100) / 100;
    row.getCell(5).value = Math.round(total * 100) / 100;
    row.getCell(6).value = projectTotal > 0 ? total / projectTotal : 0;
    for (let c = 1; c <= 6; c++) {
      row.getCell(c).border = allBorders;
      row.getCell(c).font = { name: 'Arial', size: 10 };
      if (c >= 3 && c <= 5) row.getCell(c).numFmt = currFmt;
      if (c === 6) row.getCell(c).numFmt = '0.0%';
      if (c === 1 || c === 6) row.getCell(c).alignment = { horizontal: 'center' };
      if (c === 3 || c === 4 || c === 5) row.getCell(c).alignment = { horizontal: 'right' };
    }
  });

  // Grand total
  const gt = ts.getRow(r++);
  gt.getCell(2).value = 'GRAND TOTAL';
  gt.getCell(3).value = Math.round(parsed.grand.labour * labourMult * 100) / 100;
  gt.getCell(4).value = Math.round(parsed.grand.materials * matMult * 100) / 100;
  gt.getCell(5).value = Math.round(projectTotal * 100) / 100;
  gt.getCell(6).value = 1;
  for (let c = 1; c <= 6; c++) {
    gt.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    gt.getCell(c).border = allBorders;
    gt.getCell(c).font = { name: 'Arial', size: 11, bold: true };
    if (c >= 3 && c <= 5) gt.getCell(c).numFmt = currFmt;
    if (c === 6) gt.getCell(c).numFmt = '0.0%';
    if (c === 3 || c === 4 || c === 5) gt.getCell(c).alignment = { horizontal: 'right' };
  }

  ts.views = [{ state: 'frozen', ySplit: 5 }];

  // ─── Tab 2: Materials Schedule ────────────────────────────────────────────
  const ms = wb.addWorksheet('Materials Schedule', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  });
  ms.columns = [
    { key: 'item', width: 8 },
    { key: 'desc', width: 50 },
    { key: 'unit', width: 8 },
    { key: 'qty', width: 10 },
    { key: 'mat', width: 16 },
  ];
  titleBlock(ms, 'MATERIALS SCHEDULE', 'E');
  const msHdr = ms.getRow(5);
  msHdr.values = ['Item', 'Description', 'Unit', 'Qty', 'Materials (' + currency + ')'];
  for (let c = 1; c <= 5; c++) {
    const cell = msHdr.getCell(c);
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  msHdr.height = 24;

  let mr = 6;
  let materialsRunning = 0;
  parsed.sections.forEach((s) => {
    const itemsWithMat = s.items.filter((i) => (i.materials || 0) > 0);
    if (!itemsWithMat.length) return;
    // Section row
    const sec = ms.getRow(mr++);
    ms.mergeCells('A' + (mr - 1) + ':E' + (mr - 1));
    sec.getCell(1).value = sanitizeXmlText(s.title).toUpperCase();
    sec.getCell(1).font = { name: 'Arial', size: 10, bold: true, color: { argb: '1B2A4A' } };
    sec.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
    sec.getCell(1).border = allBorders;
    sec.height = 20;

    let sectionMat = 0;
    for (const it of itemsWithMat) {
      const matVal = it.materials * matMult;
      sectionMat += matVal;
      const row = ms.getRow(mr++);
      row.getCell(1).value = sanitizeXmlText(it.itemRef);
      row.getCell(2).value = sanitizeXmlText(it.description);
      row.getCell(3).value = sanitizeXmlText(it.unit);
      row.getCell(4).value = it.qty;
      row.getCell(5).value = Math.round(matVal * 100) / 100;
      for (let c = 1; c <= 5; c++) {
        row.getCell(c).border = allBorders;
        row.getCell(c).font = { name: 'Arial', size: 10 };
        if (c === 5) {
          row.getCell(c).numFmt = currFmt;
          row.getCell(c).alignment = { horizontal: 'right' };
        }
        if (c === 1 || c === 3) row.getCell(c).alignment = { horizontal: 'center' };
        if (c === 4) {
          row.getCell(c).numFmt = '#,##0.00';
          row.getCell(c).alignment = { horizontal: 'center' };
        }
        if (c === 2) row.getCell(c).alignment = { wrapText: true, vertical: 'top' };
      }
    }
    materialsRunning += sectionMat;

    const sub = ms.getRow(mr++);
    sub.getCell(2).value = 'Subtotal — ' + sanitizeXmlText(s.title);
    sub.getCell(5).value = Math.round(sectionMat * 100) / 100;
    for (let c = 1; c <= 5; c++) {
      sub.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
      sub.getCell(c).border = allBorders;
      sub.getCell(c).font = { name: 'Arial', size: 10, bold: true };
      if (c === 5) {
        sub.getCell(c).numFmt = currFmt;
        sub.getCell(c).alignment = { horizontal: 'right' };
      }
    }
  });

  // Materials grand total
  const matGT = ms.getRow(mr++);
  matGT.getCell(2).value = 'TOTAL MATERIALS';
  matGT.getCell(5).value = Math.round(materialsRunning * 100) / 100;
  for (let c = 1; c <= 5; c++) {
    matGT.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    matGT.getCell(c).border = allBorders;
    matGT.getCell(c).font = { name: 'Arial', size: 11, bold: true };
    if (c === 5) {
      matGT.getCell(c).numFmt = currFmt;
      matGT.getCell(c).alignment = { horizontal: 'right' };
    }
  }
  ms.views = [{ state: 'frozen', ySplit: 5 }];

  // ─── Tab 3: Labour Schedule ───────────────────────────────────────────────
  const ls = wb.addWorksheet('Labour Schedule', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  });
  ls.columns = [
    { key: 'item', width: 8 },
    { key: 'desc', width: 50 },
    { key: 'unit', width: 8 },
    { key: 'qty', width: 10 },
    { key: 'lab', width: 16 },
  ];
  titleBlock(ls, 'LABOUR SCHEDULE', 'E');
  const lsHdr = ls.getRow(5);
  lsHdr.values = ['Item', 'Description', 'Unit', 'Qty', 'Labour (' + currency + ')'];
  for (let c = 1; c <= 5; c++) {
    const cell = lsHdr.getCell(c);
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.border = allBorders;
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  lsHdr.height = 24;

  let lr = 6;
  let labourRunning = 0;
  parsed.sections.forEach((s) => {
    const itemsWithLab = s.items.filter((i) => (i.labour || 0) > 0);
    if (!itemsWithLab.length) return;
    const sec = ls.getRow(lr++);
    ls.mergeCells('A' + (lr - 1) + ':E' + (lr - 1));
    sec.getCell(1).value = sanitizeXmlText(s.title).toUpperCase();
    sec.getCell(1).font = { name: 'Arial', size: 10, bold: true, color: { argb: '1B2A4A' } };
    sec.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
    sec.getCell(1).border = allBorders;
    sec.height = 20;

    let sectionLab = 0;
    for (const it of itemsWithLab) {
      const labVal = it.labour * labourMult;
      sectionLab += labVal;
      const row = ls.getRow(lr++);
      row.getCell(1).value = sanitizeXmlText(it.itemRef);
      row.getCell(2).value = sanitizeXmlText(it.description);
      row.getCell(3).value = sanitizeXmlText(it.unit);
      row.getCell(4).value = it.qty;
      row.getCell(5).value = Math.round(labVal * 100) / 100;
      for (let c = 1; c <= 5; c++) {
        row.getCell(c).border = allBorders;
        row.getCell(c).font = { name: 'Arial', size: 10 };
        if (c === 5) {
          row.getCell(c).numFmt = currFmt;
          row.getCell(c).alignment = { horizontal: 'right' };
        }
        if (c === 1 || c === 3) row.getCell(c).alignment = { horizontal: 'center' };
        if (c === 4) {
          row.getCell(c).numFmt = '#,##0.00';
          row.getCell(c).alignment = { horizontal: 'center' };
        }
        if (c === 2) row.getCell(c).alignment = { wrapText: true, vertical: 'top' };
      }
    }
    labourRunning += sectionLab;

    const sub = ls.getRow(lr++);
    sub.getCell(2).value = 'Subtotal — ' + sanitizeXmlText(s.title);
    sub.getCell(5).value = Math.round(sectionLab * 100) / 100;
    for (let c = 1; c <= 5; c++) {
      sub.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
      sub.getCell(c).border = allBorders;
      sub.getCell(c).font = { name: 'Arial', size: 10, bold: true };
      if (c === 5) {
        sub.getCell(c).numFmt = currFmt;
        sub.getCell(c).alignment = { horizontal: 'right' };
      }
    }
  });

  const labGT = ls.getRow(lr++);
  labGT.getCell(2).value = 'TOTAL LABOUR';
  labGT.getCell(5).value = Math.round(labourRunning * 100) / 100;
  for (let c = 1; c <= 5; c++) {
    labGT.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
    labGT.getCell(c).border = allBorders;
    labGT.getCell(c).font = { name: 'Arial', size: 11, bold: true };
    if (c === 5) {
      labGT.getCell(c).numFmt = currFmt;
      labGT.getCell(c).alignment = { horizontal: 'right' };
    }
  }
  ls.views = [{ state: 'frozen', ySplit: 5 }];

  // Footer on every tab
  for (const tab of [ts, ms, ls]) {
    tab.headerFooter.oddFooter =
      '&LThe AI QS — BUILDER PACK (TESTING)&RPage &P of &N';
  }

  const buffer = await writeXlsxBuffer(wb);
  return Buffer.from(buffer);
}

/**
 * Generate an upgraded "Client Copy" — per-trade OH&P, optional flat prelims,
 * optional day-rate / management-fee line, configurable rounding.
 *
 * opts:
 *   currency:        '£' | '€'
 *   contingency:     number  (% on construction net, default 0)
 *   overhead_pct:    number  (% overhead, baked into rates; default 0)
 *   profit_pct:      number  (% profit on net+overhead, baked into rates; default 0)
 *   default_ohp:     number  (legacy single OH&P; used as overhead_pct when the
 *                             split overhead/profit aren't supplied)
 *   vat:             number  (% on the post-uplift, post-contingency total)
 *   per_trade_ohp:   { [tradeNumber: string]: number }   override OH&P per section
 *   prelims_amount:  number  (£ flat — appears as a separate summary line)
 *   prelims_pct:     number  (% of net — alternative to flat amount)
 *   day_rate:        { label: string, days: number, rate_per_day: number }
 *   rounding:        0 | 1 | 10 | 100  (round each item total to nearest)
 *   project_name, client_name
 */
async function generateClientCopyPro(parsed, opts = {}) {
  const currency = opts.currency || '£';
  const contingency = parseFloat(opts.contingency) || 0;
  const defaultOhp = parseFloat(opts.default_ohp) || 0;
  // Overhead and profit are applied the way a tender summary applies them:
  // profit sits on (net + overhead), so the two compound. They're baked into
  // the client's line rates (no margin shown separately). `overhead_pct` falls
  // back to the legacy single `default_ohp` when a caller hasn't split them.
  const overheadPct = Number.isFinite(parseFloat(opts.overhead_pct)) ? parseFloat(opts.overhead_pct) : defaultOhp;
  const profitPct = parseFloat(opts.profit_pct) || 0;
  const vat = parseFloat(opts.vat) || 0;
  const perTradeOhp = opts.per_trade_ohp || {};
  const prelimsAmount = parseFloat(opts.prelims_amount) || 0;
  const prelimsPct = parseFloat(opts.prelims_pct) || 0;
  const rounding = [0, 1, 10, 100].includes(parseInt(opts.rounding, 10)) ? parseInt(opts.rounding, 10) : 0;
  const dayRate = opts.day_rate && opts.day_rate.days > 0 && opts.day_rate.rate_per_day > 0
    ? { label: opts.day_rate.label || 'Day-rate / management', days: parseFloat(opts.day_rate.days), rate_per_day: parseFloat(opts.day_rate.rate_per_day) }
    : null;
  const projectName = opts.project_name || 'Project';
  const clientName = opts.client_name || 'Client';

  function roundMoney(v) {
    // rounding 0 = penny-accurate: keep full precision so the summed totals
    // reconcile to the penny with the delivered tender (Excel still shows 2 dp).
    if (!rounding || rounding < 1) return v;
    return Math.round(v / rounding) * rounding;
  }
  // Combined overhead+profit uplift for a section, as a multiplier (e.g. 1.32825
  // for 15.5% overhead + 15% profit). A per-trade override, when present, is the
  // single combined % for that trade.
  const baseUpliftFactor = (1 + overheadPct / 100) * (1 + profitPct / 100);
  function upliftFactorForSection(sectionNumber) {
    if (Object.prototype.hasOwnProperty.call(perTradeOhp, sectionNumber)) {
      const v = parseFloat(perTradeOhp[sectionNumber]);
      if (Number.isFinite(v)) return 1 + v / 100;
    }
    return baseUpliftFactor;
  }
  // The same uplift expressed as a percentage, for the section-header note only.
  const baseCombinedPct = Math.round((baseUpliftFactor - 1) * 1e4) / 100;
  function combinedPctForSection(sectionNumber) {
    return Math.round((upliftFactorForSection(sectionNumber) - 1) * 1e4) / 100;
  }

  // ── Branding via the shared style pack ───────────────────────────────────
  const docTpl = require('./docTemplates');
  const branding = opts.branding || {};
  const style = docTpl.styleFor(branding);
  const f = style.flavour;
  const PRIMARY = style.PRIMARY;
  const ACCENT  = style.ACCENT;
  const headingFont = f.headingFont;
  const bodyFont = f.bodyFont;
  const BORDER_COL = 'FFCBD5E1';
  const thin = { style: 'thin', color: { argb: BORDER_COL } };
  const allBorders = { top: thin, bottom: thin, left: thin, right: thin };
  const currFmt = '#,##0.00';

  const wb = new ExcelJS.Workbook();
  wb.creator = (branding.company_name || 'The AI QS') + ' — Client Copy';
  wb.created = new Date();

  // We need totals to pass to the cover renderer up-front. Compute the full
  // ex-VAT figure (construction net + prelims + day-rate + contingency) so the
  // headline on the cover matches the bottom of the BOQ.
  let preNet = 0, preNetOriginal = 0, preLabour = 0, preMaterials = 0, preItemCount = 0;
  for (const s of (parsed.sections || [])) {
    const factor = upliftFactorForSection(s.number);
    for (const it of (s.items || [])) {
      preLabour += (parseFloat(it.labour) || 0);
      preMaterials += (parseFloat(it.materials) || 0);
      const base = (parseFloat(it.labour) || 0) + (parseFloat(it.materials) || 0) || (parseFloat(it.total) || 0);
      preNetOriginal += base;
      preNet += roundMoney(base * factor);
      preItemCount++;
    }
  }
  let preExVat = preNet;
  if (prelimsAmount > 0) preExVat += prelimsAmount;
  if (prelimsPct > 0)    preExVat += preNetOriginal * (prelimsPct / 100);
  if (dayRate)           preExVat += dayRate.days * dayRate.rate_per_day;
  if (contingency > 0)   preExVat += preNetOriginal * (contingency / 100);
  const preInclVat = preExVat * (1 + (vat / 100));

  // ── Cover sheet ───────────────────────────────────────────────────────────
  // TEMPORARILY DISABLED. The branded cover (renderCoverSheet) produces a sheet
  // that real Excel rejects with "We found a problem with some content" and
  // strips on open — even though the XML is well-formed and passes saxes,
  // openpyxl and ExcelJS. The data sheet below (with its branded hero header)
  // opens cleanly, so we ship that to guarantee the file works while the exact
  // cover defect (only structural difference: multi-row merged cells) is fixed.
  const INCLUDE_COVER = false;
  if (INCLUDE_COVER) {
    await docTpl.renderCoverSheet(wb, {
      docKind: 'BILL OF QUANTITIES — CLIENT COPY',
      projectName,
      clientName,
      issuedDate: new Date(),
      currency,
      totals: { exVat: preExVat, inclVat: preInclVat, labour: preLabour, materials: preMaterials },
      itemCount: preItemCount,
      sectionCount: (parsed.sections || []).length,
    }, style);
  }

  // ── Client Copy detail sheet ─────────────────────────────────────────────
  const ws = wb.addWorksheet('Client Copy', {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
    views: [{ showGridLines: false }],
  });

  ws.columns = [
    { key: 'item', width: 8 },
    { key: 'desc', width: 56 },
    { key: 'unit', width: 7 },
    { key: 'qty', width: 9 },
    { key: 'rate', width: 12 },
    { key: 'total', width: 14 },
  ];

  // Hero block (shared)
  let r = docTpl.renderHeroBlock(ws, {
    docKind: 'BILL OF QUANTITIES — CLIENT COPY',
    projectName,
    clientName,
    extraMeta: branding.company_name ? 'Issued by ' + branding.company_name : '',
  }, style, 'F');

  // Logo — top-right of the hero band. The cover sheet is disabled, so the
  // brand mark lives here on the single-sheet client copy. resolveLogo always
  // returns a validated raster (or null), so this can't corrupt the workbook.
  try {
    const logoForHero = await docTpl.resolveLogo(branding);
    if (logoForHero) {
      docTpl.embedResolvedLogo(wb, ws, logoForHero, { col: 4.55, row: 0.15 }, { maxWidth: 115, maxHeight: 44 });
    }
  } catch (e) { /* logo is optional — never block the document */ }

  ws.getRow(r).height = 6;
  r++;

  // Header row
  const hdr = ws.getRow(r);
  hdr.values = ['Item', 'Description', 'Unit', 'Qty', 'Rate (' + currency + ')', 'Total (' + currency + ')'];
  for (let c = 1; c <= 6; c++) {
    const cell = hdr.getCell(c);
    if (style.template === 'modern') {
      cell.font = { name: headingFont, size: 10.5, bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PRIMARY } };
      cell.border = allBorders;
    } else {
      cell.font = { name: headingFont, size: 10.5, bold: true, color: { argb: PRIMARY } };
      cell.border = {
        top: { style: 'thin', color: { argb: PRIMARY } },
        bottom: { style: 'medium', color: { argb: PRIMARY } },
      };
    }
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  }
  hdr.height = 28;
  r++;

  // Set sectionFill/subtotalFill to use flavour
  const SECTION_BG = f.sectionFill;
  const SUBTOTAL_BG = f.subtotalFill === style.WHITE ? PRIMARY : f.subtotalFill;

  // Per-section item rows. Each section has its own OH&P; line totals are
  // (labour + materials) × (1 + ohp/100), rounded as configured.
  const sectionTotals = []; // post-uplift per section
  let originalNet = 0;      // pre-uplift construction net (contingency base)
  parsed.sections.forEach((s, idx) => {
    const sectionFactor = upliftFactorForSection(s.number);
    const sectionCombinedPct = combinedPctForSection(s.number);

    // Section header — same flavour-driven treatment as boqGenerator
    const sec = ws.getRow(r);
    ws.mergeCells('A' + r + ':F' + r);
    sec.getCell(1).value = '   ' + s.number + '.   ' + sanitizeXmlText(s.title).toUpperCase() +
      (Math.abs(sectionCombinedPct - baseCombinedPct) > 0.001 ? '   (uplift ' + sectionCombinedPct + '%)' : '');
    sec.getCell(1).font = { name: headingFont, size: 11, bold: true, color: { argb: f.sectionText } };
    if (f.sectionFill !== style.WHITE) {
      sec.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: f.sectionFill } };
    } else {
      sec.getCell(1).border = {
        top: { style: 'medium', color: { argb: PRIMARY } },
        bottom: { style: 'thin', color: { argb: PRIMARY } },
      };
    }
    sec.height = 26;
    r++;

    let sectionTotal = 0;
    for (const it of s.items) {
      const baseLineTotal = (it.labour || 0) + (it.materials || 0) || (it.total || 0);
      originalNet += baseLineTotal;
      const upliftedTotal = roundMoney(baseLineTotal * sectionFactor);
      sectionTotal += upliftedTotal;
      const upliftedRate = it.qty > 0 ? upliftedTotal / it.qty : (it.rate || 0) * sectionFactor;

      const row = ws.getRow(r);
      row.getCell(1).value = sanitizeXmlText(it.itemRef || '');
      row.getCell(2).value = sanitizeXmlText(it.description);
      row.getCell(3).value = sanitizeXmlText(it.unit);
      row.getCell(4).value = it.qty;
      row.getCell(5).value = Math.round(upliftedRate * 100) / 100;
      row.getCell(6).value = upliftedTotal;
      for (let c = 1; c <= 6; c++) {
        row.getCell(c).border = allBorders;
        row.getCell(c).font = { name: 'Arial', size: 10 };
      }
      row.getCell(2).alignment = { wrapText: true, vertical: 'top' };
      row.getCell(4).numFmt = '#,##0.00';
      row.getCell(5).numFmt = currFmt;
      row.getCell(6).numFmt = currFmt;
      row.getCell(5).alignment = { horizontal: 'right' };
      row.getCell(6).alignment = { horizontal: 'right' };
      r++;
    }

    // Section subtotal
    const sub = ws.getRow(r);
    sub.getCell(2).value = 'Sub-total — ' + sanitizeXmlText(s.title);
    sub.getCell(6).value = sectionTotal;
    for (let c = 1; c <= 6; c++) {
      if (f.subtotalFill !== style.WHITE) {
        sub.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: f.subtotalFill } };
        sub.getCell(c).border = allBorders;
      } else {
        sub.getCell(c).border = {
          top: { style: 'thin', color: { argb: PRIMARY } },
          bottom: { style: 'thin', color: { argb: PRIMARY } },
        };
      }
      sub.getCell(c).font = { name: bodyFont, size: 10, bold: true, color: { argb: f.subtotalText } };
      if (c === 6) {
        sub.getCell(c).numFmt = currFmt;
        sub.getCell(c).alignment = { horizontal: 'right' };
      }
    }
    r++;
    r++; // blank
    sectionTotals.push({ section: s, total: sectionTotal });
  });

  // ── Summary block ──────────────────────────────────────────────────────
  const netConstruction = sectionTotals.reduce((a, x) => a + x.total, 0);

  const sumHdr = ws.getRow(r);
  ws.mergeCells('A' + r + ':F' + r);
  sumHdr.getCell(1).value = 'PROJECT SUMMARY';
  sumHdr.getCell(1).font = { name: headingFont, size: 11, bold: true, color: { argb: PRIMARY } };
  sumHdr.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SECTION_BG } };
  sumHdr.getCell(1).border = allBorders;
  r++;

  function addSummaryLine(label, value, opt = {}) {
    const row = ws.getRow(r++);
    row.getCell(2).value = label;
    row.getCell(2).font = { name: 'Arial', size: 10, bold: !!opt.bold };
    row.getCell(6).value = value;
    row.getCell(6).numFmt = currFmt;
    row.getCell(6).font = { name: 'Arial', size: 10, bold: !!opt.bold };
    row.getCell(6).border = allBorders;
    row.getCell(6).alignment = { horizontal: 'right' };
    if (opt.fill) {
      for (let c = 1; c <= 6; c++) {
        row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL_BG } };
        row.getCell(c).border = allBorders;
      }
    }
    return row;
  }

  addSummaryLine('Net construction cost (incl. trade OH&P)', netConstruction);

  let runningTotal = netConstruction;

  if (prelimsAmount > 0) {
    addSummaryLine('Preliminaries (flat)', prelimsAmount);
    runningTotal += prelimsAmount;
  }
  if (prelimsPct > 0) {
    const v = originalNet * (prelimsPct / 100);
    addSummaryLine('Preliminaries (' + prelimsPct + '% of net)', v);
    runningTotal += v;
  }
  if (dayRate) {
    const v = dayRate.days * dayRate.rate_per_day;
    addSummaryLine(dayRate.label + ' (' + dayRate.days + ' day' + (dayRate.days === 1 ? '' : 's') + ' @ ' + currency + dayRate.rate_per_day + ')', v);
    runningTotal += v;
  }
  if (contingency > 0) {
    const v = originalNet * (contingency / 100);
    addSummaryLine('Contingency (' + contingency + '% of net)', v);
    runningTotal += v;
  }

  const exVat = runningTotal;
  addSummaryLine('TOTAL (EXCL. VAT)', exVat, { bold: true, fill: true });

  if (vat > 0) {
    const vatVal = exVat * (vat / 100);
    addSummaryLine('VAT @ ' + vat + '%', vatVal);
    addSummaryLine('TOTAL (INCL. VAT)', exVat + vatVal, { bold: true, fill: true });
  }

  // Footer note
  r++;
  const note = ws.getRow(r);
  note.getCell(2).value =
    'This document is prepared for client use. Rates are final and inclusive of overheads and profit'
    + (vat > 0 ? ', with VAT as shown' : '')
    + '. No contractor margin is shown separately.';
  note.getCell(2).font = { name: bodyFont, size: 9, italic: true, color: { argb: 'FF888888' } };

  ws.views = [{ state: 'frozen', ySplit: 4, activeCell: 'A5' }];
  const footerLeft = branding.footer_text || branding.company_name || 'The AI QS';
  ws.headerFooter.oddFooter = '&L' + footerLeft + ' — CLIENT COPY&RPage &P of &N';

  const buffer = await writeXlsxBuffer(wb);
  return Buffer.from(buffer);
}

module.exports = { parseBOQ, generateBuilderPack, generateClientCopyPro };
